# Generated by Django 2.2.3 on 2020-01-29 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_profile_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255, null=True)),
                ('due_date', models.DateField(default='01/29/2020', null=True)),
                ('uploaded_file', models.FileField(upload_to='uploads/bidfiles')),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('archive', models.BooleanField(default=False)),
                ('created_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Person')),
            ],
            options={
                'verbose_name': 'Bid Files Management',
                'verbose_name_plural': 'Bid Files Management',
                'ordering': ['-due_date'],
            },
        ),
    ]
