# Generated by Django 4.2.11 on 2024-05-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(default='05/11/2024', null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/bidfiles')),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('archive', models.BooleanField(default=False)),
                ('hidden_for_customer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Bid Files Management',
                'verbose_name_plural': 'Bid Files Management',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSubmittal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='uploads/equipmentsubmittal')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('bidfile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidfilemgm.bidfile')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
