# Generated by Django 5.1.6 on 2025-03-02 18:36

import django.utils.timezone
import mysite.bidfilemgm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('uploaded_file', models.FileField(upload_to=mysite.bidfilemgm.models.bid_attachment_upload_path)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='BidFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'TAB'), (1, 'Mechanical'), (2, 'Electrical'), (3, 'Plumbing')], default=0)),
                ('due_date', models.DateField(null=True)),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('hidden_for_customer', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Bid Files Management',
                'verbose_name_plural': 'Bid Files Managements',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSubmittal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('uploaded_file', models.FileField(upload_to='uploads/equipmentsubmittal/')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
