# Generated by Django 3.0.2 on 2020-05-28 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidfilemgm', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bidfile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidfile',
            name='customer',
            field=models.ForeignKey(help_text='Maximum Upload Size: 250.0MB', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Person'),
        ),
        migrations.AddField(
            model_name='bidfile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Project'),
        ),
    ]
