# Generated by Django 4.2.11 on 2024-05-11 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidfilemgm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidfile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidfile',
            name='customer',
            field=models.ForeignKey(help_text='Maximum Upload Size: 500.0MB', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person'),
        ),
        migrations.AddField(
            model_name='bidfile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project'),
        ),
    ]
