# Generated by Django 5.1.6 on 2025-03-02 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidfilemgm', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bidattachment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidfile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidfile',
            name='customer',
            field=models.ForeignKey(help_text='Maximum Upload Size: 500.0MB', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person'),
        ),
        migrations.AddField(
            model_name='bidfile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project'),
        ),
        migrations.AddField(
            model_name='bidattachment',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bidfilemgm.bidfile'),
        ),
        migrations.AddField(
            model_name='equipmentsubmittal',
            name='bidfile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidfilemgm.bidfile'),
        ),
        migrations.AddField(
            model_name='equipmentsubmittal',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
