# Generated by Django 2.2.3 on 2020-02-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bidfilemgm', '0002_auto_20200209_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidfile',
            name='hidden_for_customer',
            field=models.BooleanField(default=False),
        ),
    ]
