# Generated by Django 3.0.2 on 2020-06-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0003_auto_20200530_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='06/23/2020', null=True),
        ),
    ]
