# Generated by Django 2.2.3 on 2020-11-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0004_auto_20201031_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='11/05/2020', null=True),
        ),
    ]
