# Generated by Django 3.0.2 on 2020-06-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0004_auto_20200623_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='06/24/2020', null=True),
        ),
    ]
