# Generated by Django 2.2.3 on 2020-11-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0005_auto_20201105_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='11/07/2020', null=True),
        ),
    ]
