# Generated by Django 2.2.3 on 2020-02-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bidfilemgm', '0005_auto_20200214_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/bidfiles'),
        ),
    ]
