# Generated by Django 2.2.3 on 2020-02-14 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bidfilemgm', '0006_auto_20200214_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='core.Project'),
        ),
    ]
