# Generated by Django 3.1.3 on 2020-11-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0007_auto_20201111_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='11/12/2020', null=True),
        ),
    ]
