# Generated by Django 2.2.3 on 2020-02-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0007_auto_20200214_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='02/18/2020', null=True),
        ),
    ]
