# Generated by Django 2.2.3 on 2020-02-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bidfilemgm', '0008_auto_20200218_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='02/21/2020', null=True),
        ),
    ]
