# Generated by Django 2.2.3 on 2020-03-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bidfilemgm', '0009_auto_20200221_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='03/01/2020', null=True),
        ),
    ]
