# Generated by Django 4.2.11 on 2024-07-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0011_alter_bidfile_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='07/25/2024', null=True),
        ),
    ]
