# Generated by Django 2.2.3 on 2020-03-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bidfilemgm', '0011_auto_20200303_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='03/05/2020', null=True),
        ),
        migrations.AlterField(
            model_name='bidfile',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='Maximum Upload Size: 2.5MB', null=True,
                                   upload_to='uploads/bidfiles'),
        ),
    ]
