# Generated by Django 2.2.3 on 2020-03-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bidfilemgm', '0012_auto_20200305_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='customer',
            field=models.ForeignKey(help_text='Maximum Upload Size: 250.0MB', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='core.Person'),
        ),
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='03/10/2020', null=True),
        ),
        migrations.AlterField(
            model_name='bidfile',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/bidfiles'),
        ),
    ]
