# Generated by Django 2.2.3 on 2020-09-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0013_auto_20200927_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='09/28/2020', null=True),
        ),
    ]
