# Generated by Django 2.2.3 on 2020-03-20 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0014_auto_20200317_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='03/20/2020', null=True),
        ),
        migrations.CreateModel(
            name='EquipmentSubmittal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/bidfiles')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('bidfile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidfilemgm.BidFile')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
