# Generated by Django 2.2.3 on 2020-03-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bidfilemgm', '0015_auto_20200320_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsubmittal',
            name='uploaded_file',
            field=models.FileField(default=1, upload_to='uploads/equipmentsubmittal'),
            preserve_default=False,
        ),
    ]
