# Generated by Django 3.1.3 on 2020-12-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0015_auto_20201205_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='12/06/2020', null=True),
        ),
    ]
