# Generated by Django 2.2.3 on 2020-10-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0016_auto_20201001_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='10/04/2020', null=True),
        ),
    ]
