# Generated by Django 2.2.3 on 2020-03-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0017_auto_20200322_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='03/25/2020', null=True),
        ),
    ]
