# Generated by Django 4.2.11 on 2024-11-15 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidfilemgm', '0017_alter_bidfile_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidfile',
            options={'ordering': ['-due_date'], 'verbose_name': 'Bid Files Management', 'verbose_name_plural': 'Bid Files Managements'},
        ),
        migrations.RemoveField(
            model_name='bidfile',
            name='flag',
        ),
        migrations.AddField(
            model_name='bidfile',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='bidfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipmentsubmittal',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='equipmentsubmittal',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentsubmittal',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='equipmentsubmittal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bidfile',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AlterField(
            model_name='bidfile',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='11/15/2024', null=True),
        ),
    ]
