# Generated by Django 3.1.3 on 2020-12-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0018_auto_20201209_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='12/14/2020', null=True),
        ),
    ]
