# Generated by Django 4.2.11 on 2024-12-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0018_alter_bidfile_options_remove_bidfile_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='12/08/2024', null=True),
        ),
    ]
