# Generated by Django 2.2.3 on 2020-03-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bidfilemgm', '0018_auto_20200325_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='03/27/2020', null=True),
        ),
    ]
