# Generated by Django 4.2.11 on 2024-12-28 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0020_alter_bidfile_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipmentsubmittal',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
