# Generated by Django 4.2.11 on 2025-02-23 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidfilemgm', '0021_alter_bidfile_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidfile',
            name='uploaded_file',
        ),
        migrations.CreateModel(
            name='BidAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('uploaded_file', models.FileField(upload_to='uploads/bidfiles')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bidfilemgm.bidfile')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
