# Generated by Django 4.2.11 on 2025-02-26 20:11

from django.db import migrations, models
import mysite.bidfilemgm.models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0022_remove_bidfile_uploaded_file_bidattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidattachment',
            name='uploaded_file',
            field=models.FileField(upload_to=mysite.bidfilemgm.models.bid_attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='equipmentsubmittal',
            name='uploaded_file',
            field=models.FileField(upload_to='uploads/equipmentsubmittal/'),
        ),
    ]
