# Generated by Django 4.2.11 on 2025-02-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0023_alter_bidattachment_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidfile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'TAB'), (1, 'Mechanical'), (2, 'Electrical'), (3, 'Plumbing')], default=0),
        ),
    ]
