# Generated by Django 2.2.3 on 2021-01-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0024_auto_20210125_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='01/28/2021', null=True),
        ),
    ]
