# Generated by Django 2.2.3 on 2021-02-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0030_auto_20210223_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='02/26/2021', null=True),
        ),
    ]
