# Generated by Django 2.2.3 on 2021-03-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0033_auto_20210306_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='03/07/2021', null=True),
        ),
    ]
