# Generated by Django 2.2.3 on 2021-03-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0036_auto_20210328_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='03/29/2021', null=True),
        ),
    ]
