# Generated by Django 2.2.3 on 2021-04-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0046_auto_20210416_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
