# Generated by Django 2.2.3 on 2021-05-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0060_auto_20210518_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='05/19/2021', null=True),
        ),
    ]
