# Generated by Django 2.2.3 on 2021-05-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0062_auto_20210523_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='05/28/2021', null=True),
        ),
    ]
