# Generated by Django 2.2.3 on 2021-07-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0066_auto_20210603_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='07/23/2021', null=True),
        ),
    ]
