# Generated by Django 2.2.3 on 2021-06-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0069_auto_20210615_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='06/23/2021', null=True),
        ),
    ]
