# Generated by Django 2.2.3 on 2021-08-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0069_auto_20210729_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='08/03/2021', null=True),
        ),
    ]
