# Generated by Django 2.2.3 on 2021-08-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0070_auto_20210803_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='08/06/2021', null=True),
        ),
    ]
