# Generated by Django 2.2.3 on 2021-08-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0072_auto_20210809_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='08/10/2021', null=True),
        ),
    ]
