# Generated by Django 3.1.5 on 2021-07-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0074_auto_20210713_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='07/18/2021', null=True),
        ),
    ]
