# Generated by Django 2.2.3 on 2021-11-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0078_auto_20211024_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='11/16/2021', null=True),
        ),
    ]
