# Generated by Django 2.2.3 on 2022-03-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0079_auto_20211116_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='03/19/2022', null=True),
        ),
    ]
