# Generated by Django 3.2.13 on 2022-05-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0086_merge_20220429_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='05/03/2022', null=True),
        ),
    ]
