# Generated by Django 3.2.13 on 2023-07-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0089_alter_bidfile_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidfile',
            name='due_date',
            field=models.DateField(default='07/06/2023', null=True),
        ),
    ]
