from django.urls import path

from mysite.estimator import views

urlpatterns = [
    path('estimate/', views.estimate_list, name='estimatorHome'),
    path('quotation/', views.quotation_list, name='quotationHome'),
    path('proposal/', views.proposal_list, name='proposalHome'),
    path('estimate/add/', views.estimator_add, name='estimatorAdd'),
    path('estimate/edit/<int:estimate_id>/', views.estimator_edit, name='estimatorEdit'),
    path('estimate/add/<int:bfm_id>/', views.estimator_add, name='estimateAddUsingBFM'),
    path('quote/add/', views.quote_add, name='quoteAdd'),
    path('quote/add/<int:estimate_id>/', views.quote_add, name='quoteAddUsingEstimate'),
    path('proposal/add/', views.proposal_add, name='proposalAdd'),
    path('proposal/add/<int:quote_id>/', views.proposal_add, name='proposalAddUsingQuote'),
    path('estimator/archive/<int:estimate_id>/', views.estimate_archive, name='estimateArchive'),
    path('quote/archive/<int:quote_id>/', views.quote_archive, name='quoteArchive'),
    path('proposal/archive/<int:proposal_id>/', views.proposal_archive, name='proposalArchive'),
    path('estimate/delete/<int:estimate_id>/', views.estimate_delete, name='estimateDelete'),
    path('quote/delete/<int:quote_id>/', views.quote_delete, name='quoteDelete'),
    path('proposal/delete/<int:proposal_id>/', views.proposal_delete, name='proposalDelete'),
    path('company/customer/create/', views.company_customer_create_popup, name="companyCustomerCreate"),
    path('company/customer/<int:pk>/edit/', views.company_customer_edit_popup, name="companyCustomerEdit"),
    path('company/customer/<int:pk>/archive/', views.company_customer_archive, name="companyCustomerArchive"),
    path('company/engineer/create/', views.company_engineer_create_popup, name="companyEngineerCreate"),
    path('company/engineer/<int:pk>/edit/', views.company_engineer_edit_popup, name="companyEngineerEdit"),
    path('company/ajax/get_company_id/', views.get_company_id, name="get_company_id"),
    path('customer_person/create/', views.customer_person_create_popup, name="customerPersonCreate"),
    path('customer_person/<int:pk>/edit/', views.customer_person_edit_popup, name="customerPersonEdit"),
    path('engineer_person/create/', views.engineer_person_create_popup, name="engineerPersonCreate"),
    path('engineer_person/<int:pk>/edit/', views.engineer_person_edit_popup, name="engineerPersonEdit"),
    path('manufacturerPerson/<int:pk>/edit/', views.manufacturer_person_edit_popup, name="manufacturerPersonEdit"),
    path('person/ajax/get_person_id/', views.get_person_id, name="get_person_id"),
    path('project/create/', views.project_create_popup, name="projectCreate"),
    path('project/<int:pk>/edit/', views.project_edit_popup, name="projectEdit"),
    path('project/ajax/get_project_id/', views.get_project_id, name="get_project_id"),
    path('engineer/create/', views.engineer_create_popup, name="engineerCreate"),
    path('engineer/<int:pk>/edit/', views.engineer_edit_popup, name="engineerEdit"),
    path('engineer/ajax/get_person_id/', views.get_engineer_id, name="get_engineer_id"),
    path('estimator/equipment/<int:estimate_id>/<int:estimate_service_id>/', views.estimate_equipment, name='estimateEquipment'),
    path('estimator/equipment/delete/<int:estimate_equipment_id>/<int:interval_id>/', views.estimate_equipment_delete, name='estimateEquipmentDelete'),
    path('estimator/details/<int:estimate_id>/', views.estimate_details, name='estimateDetails'),
    path('estimator/estimate/<int:estimate_id>/', views.estimate_bid, name='estimateBid'),
    path('estimate/duplicate/<int:estimate_id>/', views.estimate_duplicate, name='estimateDuplicate'),
]
