# Generated by Django 2.2.3 on 2021-06-24 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetvavboxfanheatschedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vbfhsequipment',
            name='main_data_entry_completed',
        ),
    ]
