# Generated by Django 2.2.3 on 2021-06-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetvavboxfanheatschedule', '0002_remove_vbfhsequipment_main_data_entry_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbfhssheetdata',
            name='data_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Design'), (2, 'Actual')], default=1),
        ),
    ]
