volumes:
  postgres_data_dev_itab: {}
  postgres_data_backups_dev_itab: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/dev/django/Dockerfile
    image: django_dev_itab
    container_name: django_dev_itab
    depends_on:
      - postgres
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./docker/prod/postgres/Dockerfile
    image: postgres_prod_itab
    container_name: postgres_prod_itab
    volumes:
      - postgres_data_dev_itab:/var/lib/postgresql/data
      - postgres_data_backups_dev_itab:/backups
    env_file:
      - ./.envs/.dev/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: mailpit_dev_itab
    ports:
      - "8025:8025"
