volumes:
  itab_dev_postgres_data: {}
  itab_dev_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/dev/django/Dockerfile
    image: itab_dev_django
    container_name: itab_dev_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - mysite/.env
    ports:
      - '8001:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./docker/prod/postgres/Dockerfile
    image: itab_prod_postgres
    container_name: itab_prod_postgres
    volumes:
      - itab_dev_postgres_data:/var/lib/postgresql/data
      - itab_dev_postgres_data_backups:/backups
    env_file:
      - mysite/.env
    ports:
      - '8002:5432'
