volumes:
  itab_prod_postgres_data: {}
  itab_prod_postgres_data_backups: {}
  itab_prod_django_media: {}
  itab_prod_traefik: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/prod/django/Dockerfile

    image: django_prod_itab
    volumes:
      - itab_prod_django_media:/app/media
    depends_on:
      - postgres
    env_file:
      - ./.envs/.prod/.django
      - ./.envs/.prod/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./docker/prod/postgres/Dockerfile
    image: postgres_prod_itab
    volumes:
      - itab_prod_postgres_data:/var/lib/postgresql/data
      - itab_prod_postgres_data_backups:/backups
    env_file:
      - ./.envs/.prod/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./docker/prod/traefik/Dockerfile
    image: itab_prod_traefik
    depends_on:
      - django
    volumes:
      - itab_prod_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'

  nginx:
    build:
      context: .
      dockerfile: ./docker/prod/nginx/Dockerfile
    image: nginx_dev_itab
    depends_on:
      - django
    volumes:
      - itab_prod_django_media:/usr/share/nginx/media:ro
