version: '3'

volumes:
  postgres_data_stag_itab: {}
  postgres_data_backups_stag_itab: {}
  django_media_stag_itab: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/stag/django/Dockerfile
    image: itab-django-stag
    volumes:
      - django_media_stag_itab:/app/media
    depends_on:
      - postgres
    env_file:
      - ./.envs/.stag/.django
      - ./.envs/.stag/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./docker/prod/postgres/Dockerfile
    image: itab-postgres-prod
    volumes:
      - itab_stag_postgres_data:/var/lib/postgresql/data
      - itab_stag_postgres_data_backups:/backups
    env_file:
      - ./.envs/.stag/.postgres
