# Generated by Django 4.2.11 on 2024-05-11 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbmanagement', '0001_initial'),
        ('sheetcreator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionUnitEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_data_entry_completed', models.BooleanField(default=False)),
                ('actual_data_entry_completed', models.BooleanField(default=False)),
                ('field_order', models.PositiveIntegerField(default=0)),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipment')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.datasheet')),
            ],
            options={
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='InductionUnitSheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.PositiveSmallIntegerField(choices=[(1, 'Design'), (2, 'Actual')], default=1)),
                ('value', models.CharField(max_length=500)),
                ('induction_unit_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsheetinductionunit.inductionunitequipment')),
                ('sheet_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheetfield')),
            ],
        ),
    ]
