# Generated by Django 4.2.11 on 2024-06-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0006_alter_controlsystem_release_date'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('mail', models.EmailField(blank=True, max_length=55)),
                ('web', models.CharField(blank=True, max_length=55)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=55)),
                ('state', models.CharField(blank=True, max_length=55)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sheet_generator', models.BooleanField(default=False)),
                ('flag', models.BooleanField(default=True)),
                ('form_fields', models.JSONField()),
                ('inheritance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.testsheet')),
            ],
            options={
                'verbose_name': 'Test Sheet',
                'verbose_name_plural': 'Test Sheet',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimate_work', models.IntegerField(default=10, verbose_name='Estimate Work in Minutes')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('form_fields', models.JSONField()),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='core.service')),
                ('test_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='equipments.testsheet')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_date', models.DateField(null=True)),
                ('system', models.CharField(max_length=50)),
                ('number_of_equipment_groups', models.IntegerField(default=1)),
                ('archive', models.BooleanField(default=False)),
                ('rogue_design_data_entry_completed', models.BooleanField(default=False)),
                ('rogue_actual_data_entry_completed', models.BooleanField(default=False)),
                ('main_data_entry_confirmed', models.BooleanField(default=False)),
                ('design_data_entry_confirmed', models.BooleanField(default=False)),
                ('actual_data_entry_confirmed', models.BooleanField(default=False)),
                ('main_data_entry_completed', models.BooleanField(default=False)),
                ('design_data_entry_completed', models.BooleanField(default=False)),
                ('actual_data_entry_completed', models.BooleanField(default=False)),
                ('terminal_design_data_entry_completed', models.BooleanField(default=False)),
                ('terminal_actual_data_entry_completed', models.BooleanField(default=False)),
                ('form_fields', models.JSONField()),
                ('info', models.JSONField()),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment_submittal', models.FileField(blank=True, null=True, upload_to='uploads/equipmentDb/equipment_submittal')),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/equipmentDb/image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('equipment_group', models.CharField(default='A', max_length=50)),
                ('number_of_supply_air_terminal', models.SmallIntegerField(default=0)),
                ('name', models.CharField(max_length=10)),
                ('_default', models.CharField(blank=True, max_length=10)),
                ('size_type', models.PositiveSmallIntegerField(default=2, verbose_name='No. of Size Fields')),
                ('is_custom', models.BooleanField(default=False)),
                ('outlet_no', models.SmallIntegerField()),
                ('_type', models.PositiveSmallIntegerField(default=1)),
                ('equipment_name', models.CharField(max_length=255, null=True)),
                ('other_group', models.SmallIntegerField(blank=True, null=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sheets', to='equipments.equipment')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sheets', to='equipments.manufacturer')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.datasheet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sheets', to='order.order')),
            ],
            options={
                'verbose_name': 'Data Sheet',
                'verbose_name_plural': 'Data Sheets',
            },
        ),
    ]
