# Generated by Django 4.2.11 on 2024-06-26 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_controlsystem_release_date'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sheets', to='order.order'),
        ),
    ]
