# Generated by Django 4.2.11 on 2024-06-26 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0002_equipmentdb_actual_data_entry_confirmed_and_more'),
        ('equipments', '0002_alter_datasheet_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsheet',
            name='inheritance',
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sheets', to='dbmanagement.equipmentmanufacturer'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='test_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='dbmanagement.testsheet'),
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='TestSheet',
        ),
    ]
