# Generated by Django 4.2.11 on 2024-06-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_remove_testsheet_inheritance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='form_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='form_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
