# Generated by Django 4.2.11 on 2024-06-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_alter_datasheet_form_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
