# Generated by Django 4.2.11 on 2024-06-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_alter_datasheet_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='outlet_no',
            field=models.SmallIntegerField(default=1),
        ),
    ]
