# Generated by Django 4.2.11 on 2024-07-01 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_alter_datasheet_outlet_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sheet_generator', models.BooleanField(default=False)),
                ('flag', models.BooleanField(default=True)),
                ('form_fields', models.JSONField()),
                ('inheritance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.testsheet')),
            ],
            options={
                'verbose_name': 'Test Sheet',
                'verbose_name_plural': 'Test Sheet',
                'ordering': ['priority'],
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='test_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='equipments.testsheet'),
        ),
    ]
