# Generated by Django 4.2.11 on 2024-07-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_testsheet_alter_equipment_test_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsheet',
            name='form_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
