# Generated by Django 4.2.11 on 2024-07-01 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_alter_testsheet_form_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheet',
            name='number_of_equipment_groups',
        ),
    ]
