# Generated by Django 4.2.11 on 2024-07-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_remove_datasheet_number_of_equipment_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
