# Generated by Django 4.2.11 on 2024-07-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_alter_datasheet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
