# Generated by Django 4.2.11 on 2024-07-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0011_alter_datasheet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='number_of_exhaust_air_terminal',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='number_of_outside_air_terminal',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='number_of_return_air_terminal',
            field=models.SmallIntegerField(default=0),
        ),
    ]
