# Generated by Django 4.2.11 on 2024-07-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0012_datasheet_number_of_exhaust_air_terminal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheet',
            name='equipment_name',
        ),
        migrations.AddField(
            model_name='datasheet',
            name='area_served',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='fan_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
