# Generated by Django 4.2.11 on 2024-07-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0013_remove_datasheet_equipment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='outlet_no',
            field=models.SmallIntegerField(default=0),
        ),
    ]
