# Generated by Django 4.2.11 on 2024-08-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0014_datasheet_code_alter_datasheet_outlet_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheet',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='datasheet',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
