# Generated by Django 4.2.11 on 2024-08-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0015_remove_datasheet_serial_number_datasheet_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheet',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='datasheet',
            name='start_date',
        ),
    ]
