# Generated by Django 4.2.11 on 2024-08-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0016_remove_datasheet_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='uploads/equipments/attach'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='attach_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
