# Generated by Django 4.2.11 on 2024-11-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0017_datasheet_attach_datasheet_attach_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSheet',
        ),
    ]
