# Generated by Django 2.2.3 on 2021-05-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheetcreator', '0080_auto_20210528_1944'),
        ('dbmanagement', '0017_auto_20210116_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_number', models.CharField(blank=True, max_length=20, null=True)),
                ('main_data_entry_completed', models.BooleanField(default=False)),
                ('design_data_entry_completed', models.BooleanField(default=False)),
                ('actual_data_entry_completed', models.BooleanField(default=False)),
                ('field_order', models.PositiveIntegerField(default=0)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.EquipmentDb')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.Equipment')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.DataSheet')),
            ],
            options={
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='PumpSheetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('pump_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsheetpump.PumpEquipment')),
                ('sheet_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheetField')),
            ],
        ),
    ]
