# Generated by Django 2.2.3 on 2021-05-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetpump', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpequipment',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
