# Generated by Django 2.2.3 on 2021-05-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetpump', '0002_pumpequipment_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpsheetdata',
            name='data_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Design'), (2, 'Actual')], default=1),
        ),
    ]
