# Generated by Django 5.1.7 on 2025-03-31 15:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('statement_no', models.CharField(max_length=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('attention', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contactinfo')),
            ],
            options={
                'verbose_name': 'Account Summary List',
                'verbose_name_plural': 'Account Summary Lists',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('terms', models.CharField(blank=True, default='Due upon Receipt', max_length=255)),
                ('description', models.TextField(blank=True, default='TESTING AND BALANCING', max_length=255)),
                ('percent_of_performance_completed', models.FloatField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('invoice_type', models.SmallIntegerField(default=1)),
                ('attention', models.CharField(blank=True, max_length=255, null=True)),
                ('edited_on', models.DateField(blank=True, null=True)),
                ('mark_as_paid', models.BooleanField(default=False)),
                ('times_estimate_changed', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'Invoice List',
                'verbose_name_plural': 'Invoice Lists',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('total_invoiced', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('pdf_filename', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gi.invoice')),
            ],
            options={
                'verbose_name': 'Invoice History',
                'verbose_name_plural': 'Invoice Histories',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('payment_date', models.DateField()),
                ('payment_no', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gi.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Transactions',
                'verbose_name_plural': 'Invoice Transactions',
                'ordering': ['-created_on'],
            },
        ),
    ]
