# Generated by Django 2.2.3 on 2019-12-20 17:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField(blank=True, default='12/20/2019')),
                ('date_completed', models.DateField(blank=True, default='12/20/2019')),
                ('terms', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('percent_of_performance_completed', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('total_payment_received_to_date', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('past_due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('attention', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('mark_as_paid', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'verbose_name': 'Invoice List',
                'verbose_name_plural': 'Invoice List',
                'ordering': ['-created_on'],
            },
        ),
    ]
