# Generated by Django 3.1.3 on 2020-12-06 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payment_date', models.DateField(default='12/06/2020')),
                ('payment_no', models.CharField(blank=True, max_length=20, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gi.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Transactions',
                'verbose_name_plural': 'Invoice Transactions',
                'ordering': ['-created_on'],
            },
        ),
    ]
