# Generated by Django 2.2.3 on 2020-01-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_completed',
            field=models.DateField(blank=True, default='01/20/2020'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_started',
            field=models.DateField(blank=True, default='01/20/2020'),
        ),
    ]
