# Generated by Django 3.1.3 on 2020-12-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0002_invoicetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
