# Generated by Django 2.2.3 on 2020-02-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gi', '0003_auto_20200129_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_completed',
            field=models.DateField(blank=True, default='02/09/2020'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_started',
            field=models.DateField(blank=True, default='02/09/2020'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, default='Testing and Balancing', max_length=255),
        ),
    ]
