# Generated by Django 3.1.3 on 2020-12-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0004_auto_20201207_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsummary',
            name='statement_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountsummary',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
