# Generated by Django 2.2.3 on 2020-02-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gi', '0004_auto_20200209_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_completed',
            field=models.DateField(blank=True, default='02/11/2020'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_started',
            field=models.DateField(blank=True, default='02/11/2020'),
        ),
    ]
