# Generated by Django 3.1.3 on 2020-12-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0005_auto_20201207_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='past_due_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_payment_received_to_date',
        ),
        migrations.AlterField(
            model_name='accountsummary',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='12/09/2020'),
        ),
    ]
