# Generated by Django 2.2.3 on 2020-02-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gi', '0005_auto_20200211_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_completed',
            field=models.DateField(blank=True, default='02/14/2020'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_started',
            field=models.DateField(blank=True, default='02/14/2020'),
        ),
    ]
