# Generated by Django 4.2.11 on 2024-06-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0006_alter_invoicetransaction_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='06/30/2024'),
        ),
    ]
