# Generated by Django 3.1.3 on 2020-12-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('gi', '0006_auto_20201209_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsummary',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contactinfo'),
        ),
    ]
