# Generated by Django 2.2.3 on 2019-11-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0007_auto_20191129_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='attention',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
