# Generated by Django 3.1.3 on 2020-12-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0007_auto_20201209_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsummary',
            name='attention',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
