# Generated by Django 2.2.3 on 2020-02-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0008_auto_20200221_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
    ]
