# Generated by Django 2.2.3 on 2019-11-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0008_invoice_attention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_completed',
            field=models.DateField(blank=True, default='11/30/2019'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_started',
            field=models.DateField(blank=True, default='11/30/2019'),
        ),
    ]
