# Generated by Django 3.1.3 on 2020-12-09 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0008_accountsummary_attention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
