# Generated by Django 4.2.11 on 2024-07-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0010_alter_invoicetransaction_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='07/25/2024'),
        ),
    ]
