# Generated by Django 4.2.11 on 2024-10-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0015_alter_invoicetransaction_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='10/18/2024'),
        ),
    ]
