# Generated by Django 4.2.11 on 2024-11-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0016_alter_invoicetransaction_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='11/15/2024'),
        ),
    ]
