# Generated by Django 2.2.3 on 2021-02-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0017_auto_20210129_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='02/01/2021'),
        ),
    ]
