# Generated by Django 4.2.11 on 2024-12-08 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gi', '0017_alter_invoicetransaction_payment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsummary',
            options={'ordering': ['-created_on'], 'verbose_name': 'Account Summary List', 'verbose_name_plural': 'Account Summary Lists'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_on'], 'verbose_name': 'Invoice List', 'verbose_name_plural': 'Invoice Lists'},
        ),
        migrations.AlterModelOptions(
            name='invoicehistory',
            options={'ordering': ['created_on'], 'verbose_name': 'Invoice History', 'verbose_name_plural': 'Invoice Histories'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='2024-12-08'),
        ),
    ]
