# Generated by Django 2.2.3 on 2021-02-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0018_auto_20210201_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(blank=True, default='Due upon Receipt', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='02/16/2021'),
        ),
    ]
