# Generated by Django 4.2.11 on 2024-12-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0018_alter_accountsummary_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(),
        ),
    ]
