# Generated by Django 4.2.11 on 2024-12-28 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0019_alter_invoicetransaction_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsummary',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='accountsummary',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='accountsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invoicetransaction',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='invoicetransaction',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='invoicetransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accountsummary',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoicehistory',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
