# Generated by Django 2.2.3 on 2021-02-22 20:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0020_auto_20210222_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='02/23/2021'),
        ),
        migrations.CreateModel(
            name='InvoiceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invoiced', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('pdf_filename', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gi.Invoice')),
            ],
            options={
                'verbose_name': 'Invoice History',
                'verbose_name_plural': 'Invoice History',
                'ordering': ['-created_on'],
            },
        ),
    ]
