# Generated by Django 4.2.11 on 2025-02-23 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gi', '0020_accountsummary_archive_accountsummary_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
