# Generated by Django 2.2.3 on 2021-02-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0021_auto_20210223_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='times_estimate_changed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
