# Generated by Django 2.2.3 on 2021-02-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0022_invoice_times_estimate_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='02/26/2021'),
        ),
    ]
