# Generated by Django 2.2.3 on 2021-04-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0032_auto_20210404_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='04/07/2021'),
        ),
    ]
