# Generated by Django 2.2.3 on 2021-04-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0037_auto_20210415_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='04/16/2021'),
        ),
    ]
