# Generated by Django 2.2.3 on 2021-05-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0047_auto_20210505_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='05/06/2021'),
        ),
    ]
