# Generated by Django 2.2.3 on 2021-05-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0052_auto_20210519_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='05/23/2021'),
        ),
    ]
