# Generated by Django 2.2.3 on 2021-05-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0053_auto_20210523_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='05/28/2021'),
        ),
    ]
