# Generated by Django 2.2.3 on 2021-06-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0055_auto_20210529_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='06/01/2021'),
        ),
    ]
