# Generated by Django 2.2.3 on 2021-06-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0056_auto_20210601_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='06/03/2021'),
        ),
    ]
