# Generated by Django 2.2.3 on 2021-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0057_auto_20210603_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='06/07/2021'),
        ),
    ]
