# Generated by Django 2.2.3 on 2021-08-03 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0060_auto_20210729_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='percent_of_performance_completed',
            field=models.FloatField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='08/03/2021'),
        ),
    ]
