# Generated by Django 3.1.5 on 2021-07-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0065_auto_20210713_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='07/18/2021'),
        ),
    ]
