# Generated by Django 2.2.3 on 2021-10-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0068_auto_20211005_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, default='TESTING AND BALANCING', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='10/24/2021'),
        ),
    ]
