# Generated by Django 3.2.13 on 2022-04-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0072_auto_20220429_1045'),
        ('gi', '0076_alter_invoicetransaction_payment_date'),
    ]

    operations = [
    ]
