# Generated by Django 3.2.13 on 2022-05-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0077_merge_20220429_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicehistory',
            options={'ordering': ['created_on'], 'verbose_name': 'Invoice History', 'verbose_name_plural': 'Invoice History'},
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='05/03/2022'),
        ),
    ]
