# Generated by Django 3.2.13 on 2023-07-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0079_auto_20220522_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='edited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicetransaction',
            name='payment_date',
            field=models.DateField(default='07/05/2023'),
        ),
    ]
