# Generated by Django 3.2.13 on 2023-07-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gi', '0080_auto_20230705_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='edited_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
