# Generated by Django 2.2.3 on 2021-03-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='document',
            name='type',
        ),
        migrations.DeleteModel(
            name='TypesOfDocument',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
