# Generated by Django 2.2.3 on 2021-06-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetduct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ductsheetdata',
            old_name='pump_equipment',
            new_name='duct_equipment',
        ),
    ]
