# Generated by Django 4.2.11 on 2025-02-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidfilemgm', '0022_remove_bidfile_uploaded_file_bidattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('processed_images', models.CharField(max_length=4096, null=True)),
                ('process_variables', models.CharField(max_length=4096, null=True)),
                ('addresses', models.CharField(max_length=4096, null=True)),
                ('execution_time', models.IntegerField(null=True)),
                ('run_step', models.SmallIntegerField(default=1)),
                ('run_step_progress', models.SmallIntegerField(default=-1)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidfilemgm.bidfile')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='AddressExtractionDebug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debug_step', models.SmallIntegerField()),
                ('data', models.CharField(max_length=4096)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_analyzer.addressextractionrun')),
            ],
            options={
                'ordering': ['run', 'debug_step'],
                'unique_together': {('run', 'debug_step')},
            },
        ),
    ]
