# Generated by Django 2.2.3 on 2020-06-11 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ibfm', '0003_auto_20200611_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressExtractionRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('processed_images', models.CharField(max_length=4096, null=True)),
                ('process_variables', models.CharField(max_length=4096, null=True)),
                ('addresses', models.CharField(max_length=4096, null=True)),
                ('execution_time', models.IntegerField(null=True)),
                ('run_step', models.SmallIntegerField(default=0)),
                ('run_step_progress', models.SmallIntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibfm.iBidFile')),
            ],
        ),
        migrations.CreateModel(
            name='AddressExtractionDebug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debug_step', models.SmallIntegerField()),
                ('data', models.CharField(max_length=4096)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_analyzer.AddressExtractionRun')),
            ],
            options={
                'unique_together': {('run', 'debug_step')},
            },
        ),
    ]
