# Generated by Django 2.2.3 on 2020-06-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressextractionrun',
            name='run_step',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='addressextractionrun',
            name='run_step_progress',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
