# Generated by Django 3.0.2 on 2020-06-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_analyzer', '0002_auto_20200614_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressextractiondebug',
            options={'ordering': ['run', 'debug_step']},
        ),
        migrations.AlterModelOptions(
            name='addressextractionrun',
            options={'ordering': ['-created_on']},
        ),
    ]
