# Generated by Django 2.2.3 on 2019-12-20 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(default='12/20/2019', null=True)),
                ('confirm_date', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('archive', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cu_person', to='core.Person')),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_person', to='core.Person')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Project')),
                ('service', models.ManyToManyField(related_name='estimates', to='core.Service')),
            ],
            options={
                'verbose_name': 'Estimate List',
                'verbose_name_plural': 'Estimate List',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimator.Estimate')),
            ],
            options={
                'verbose_name': 'Quote List',
                'verbose_name_plural': 'Quote List',
                'ordering': ['-estimate'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity', models.IntegerField(default=30)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimator.Quote')),
            ],
            options={
                'verbose_name': 'Proposal List',
                'verbose_name_plural': 'Proposal List',
                'ordering': ['-quote'],
            },
        ),
        migrations.CreateModel(
            name='EstimateEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipment')),
                ('estimate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estimator.Estimate')),
            ],
            options={
                'verbose_name': 'Estimated Equipment List',
                'verbose_name_plural': 'Estimated Equipment List',
            },
        ),
        migrations.CreateModel(
            name='EstimateDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_system', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1%'), (2, '2%'), (3, '3%')], default=0)),
                ('hours', models.PositiveSmallIntegerField(choices=[(0, 'Regular'), (10, 'Saturday/Holiday'), (15, 'Sunday')], default=0)),
                ('pre_demo', models.FloatField(default=0)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('remark', models.TextField(blank=True, max_length=500)),
                ('validity', models.IntegerField(default=30)),
                ('saved_flag', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimator.Estimate')),
            ],
            options={
                'verbose_name': 'Estimated Additional info',
                'verbose_name_plural': 'Estimated Additional info',
            },
        ),
    ]
