# Generated by Django 4.2.11 on 2024-05-11 08:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidfilemgm', '0001_initial'),
        ('dbmanagement', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(default='05/11/2024', null=True)),
                ('drawing_date', models.DateField(blank=True, null=True)),
                ('confirm_date', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('archive', models.BooleanField(default=False)),
                ('bfm', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bidfilemgm.bidfile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cu_person', to='core.person')),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='en_person', to='core.person')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project')),
                ('service', models.ManyToManyField(related_name='estimates', to='core.service')),
            ],
            options={
                'verbose_name': 'Estimate List',
                'verbose_name_plural': 'Estimate List',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimator.estimate')),
            ],
            options={
                'verbose_name': 'Quote List',
                'verbose_name_plural': 'Quote List',
                'ordering': ['-estimate'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity', models.IntegerField(default=180)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimator.quote')),
            ],
            options={
                'verbose_name': 'Proposal List',
                'verbose_name_plural': 'Proposal List',
                'ordering': ['-quote'],
            },
        ),
        migrations.CreateModel(
            name='EstimateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('version', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimator.estimate')),
            ],
            options={
                'verbose_name': 'Estimate History',
                'verbose_name_plural': 'Estimate History',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='EstimateEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipment')),
                ('estimate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estimator.estimate')),
            ],
            options={
                'verbose_name': 'Estimated Equipment List',
                'verbose_name_plural': 'Estimated Equipment List',
            },
        ),
        migrations.CreateModel(
            name='EstimateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_system', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1%'), (2, '2%'), (3, '3%'), (4, '4%'), (5, '5%')], default=0)),
                ('hours', models.PositiveSmallIntegerField(choices=[(0, 'Regular Hours'), (5, 'Off Hours'), (10, 'Saturday/Holidays'), (15, 'Sunday')], default=0)),
                ('pre_demo', models.FloatField(default=0)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('customer_adjustment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('remark', models.TextField(blank=True, max_length=500)),
                ('validity', models.IntegerField(default=30)),
                ('saved_flag', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimator.estimate')),
            ],
            options={
                'verbose_name': 'Estimated Additional info',
                'verbose_name_plural': 'Estimated Additional info',
            },
        ),
    ]
