# Generated by Django 2.2.3 on 2019-12-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='12/24/2019', null=True),
        ),
    ]
