# Generated by Django 5.1.6 on 2025-04-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='service',
            new_name='services',
        ),
    ]
