# Generated by Django 2.2.3 on 2020-01-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='01/20/2020', null=True),
        ),
    ]
