# Generated by Django 2.2.3 on 2020-01-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimator', '0002_auto_20200120_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='01/29/2020', null=True),
        ),
    ]
