# Generated by Django 5.1.6 on 2025-04-09 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('estimator', '0002_rename_service_estimate_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment'),
        ),
    ]
