# Generated by Django 2.2.3 on 2019-07-08 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_auto_20190708_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='confirm_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
