# Generated by Django 2.2.3 on 2020-02-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidfilemgm', '0002_auto_20200209_2112'),
        ('estimator', '0003_auto_20200129_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='bfm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bidfilemgm.BidFile'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='02/09/2020', null=True),
        ),
    ]
