# Generated by Django 2.2.3 on 2019-07-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0003_auto_20190708_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='07-08-2019'),
        ),
    ]
