# Generated by Django 2.2.3 on 2019-07-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0004_auto_20190708_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimate',
            options={'ordering': ['-due_date'], 'verbose_name': 'Estimated General info', 'verbose_name_plural': 'Estimated General info'},
        ),
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='07-08-2019', null=True),
        ),
    ]
