# Generated by Django 3.0.2 on 2020-07-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0004_auto_20200624_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='07/11/2020', null=True),
        ),
    ]
