# Generated by Django 2.2.3 on 2019-07-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0005_auto_20190708_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='07/12/2019', null=True),
        ),
    ]
