# Generated by Django 2.2.3 on 2020-02-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0005_estimate_hidden_for_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='02/11/2020', null=True),
        ),
    ]
