# Generated by Django 2.2.3 on 2019-07-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0006_auto_20190712_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedetails',
            name='pre_demo',
            field=models.IntegerField(default=0),
        ),
    ]
