# Generated by Django 2.2.3 on 2020-02-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0006_auto_20200211_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='02/14/2020', null=True),
        ),
    ]
