# Generated by Django 3.0.2 on 2020-09-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0006_auto_20200712_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='09/14/2020', null=True),
        ),
    ]
