# Generated by Django 2.2.3 on 2019-07-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0007_auto_20190712_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateequipment',
            name='price_override',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
