# Generated by Django 2.2.3 on 2020-02-14 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0007_auto_20200214_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='bfm',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bidfilemgm.BidFile'),
        ),
    ]
