# Generated by Django 4.2.11 on 2024-07-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0007_alter_estimate_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='07/01/2024', null=True),
        ),
    ]
