# Generated by Django 2.2.3 on 2019-07-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0008_estimateequipment_price_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateequipment',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
