# Generated by Django 3.1.3 on 2020-11-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0008_auto_20201112_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='11/13/2020', null=True),
        ),
    ]
