# Generated by Django 4.2.11 on 2024-07-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0008_alter_estimate_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='07/03/2024', null=True),
        ),
    ]
