# Generated by Django 2.2.3 on 2020-02-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimator', '0008_auto_20200214_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='drawing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='02/18/2020', null=True),
        ),
    ]
