# Generated by Django 3.0.2 on 2020-09-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0009_auto_20200919_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='09/24/2020', null=True),
        ),
    ]
