# Generated by Django 2.2.3 on 2019-08-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0009_auto_20190712_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='confirm_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='08/09/2019', null=True),
        ),
    ]
