# Generated by Django 2.2.3 on 2020-02-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0009_auto_20200218_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='hidden_for_customer',
        ),
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='02/21/2020', null=True),
        ),
    ]
