# Generated by Django 3.1.3 on 2020-11-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0009_auto_20201113_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='11/14/2020', null=True),
        ),
    ]
