# Generated by Django 3.1.3 on 2020-11-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0010_auto_20201114_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='11/15/2020', null=True),
        ),
    ]
