# Generated by Django 4.2.11 on 2024-07-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0010_alter_estimate_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='07/25/2024', null=True),
        ),
    ]
