# Generated by Django 2.2.3 on 2019-09-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0010_auto_20190809_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='proposal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estimate',
            name='quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='09/11/2019', null=True),
        ),
    ]
