# Generated by Django 3.0.2 on 2020-09-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0010_auto_20200924_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='09/26/2020', null=True),
        ),
        migrations.AlterField(
            model_name='estimatedetails',
            name='hours',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Regular'), (5, 'Regular/After Hour'), (10, 'Saturday/Holiday'), (15, 'Sunday')], default=0),
        ),
    ]
