# Generated by Django 2.2.3 on 2019-09-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0011_auto_20190911_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimate',
            options={'ordering': ['-due_date'], 'verbose_name': 'Estimate List', 'verbose_name_plural': 'Estimate List'},
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='quote',
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.BooleanField(default=False)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimator.Estimate')),
            ],
            options={
                'verbose_name': 'Quote List',
                'verbose_name_plural': 'Estimated List',
                'ordering': ['-estimate'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.BooleanField(default=False)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimator.Quote')),
            ],
            options={
                'verbose_name': 'Proposal List',
                'verbose_name_plural': 'Proposal List',
                'ordering': ['-quote'],
            },
        ),
    ]
