# Generated by Django 2.2.3 on 2020-03-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimator', '0011_auto_20200301_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='03/03/2020', null=True),
        ),
        migrations.AlterField(
            model_name='estimatedetails',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
