# Generated by Django 2.2.3 on 2019-09-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0012_auto_20190911_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-estimate'], 'verbose_name': 'Quote List', 'verbose_name_plural': 'Quote List'},
        ),
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='09/12/2019', null=True),
        ),
    ]
