# Generated by Django 4.2.11 on 2024-08-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0012_alter_estimate_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='08/20/2024', null=True),
        ),
    ]
