# Generated by Django 2.2.3 on 2019-09-13 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0013_auto_20190912_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='09/13/2019', null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='estimate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimator.Estimate'),
        ),
    ]
