# Generated by Django 2.2.3 on 2020-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimator', '0013_auto_20200305_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='03/10/2020', null=True),
        ),
    ]
