# Generated by Django 2.2.3 on 2020-03-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0014_auto_20200310_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='03/17/2020', null=True),
        ),
    ]
