# Generated by Django 2.2.3 on 2019-09-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0014_auto_20190913_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateequipment',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
