# Generated by Django 2.2.3 on 2019-09-13 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0015_auto_20190913_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimator.Quote'),
        ),
    ]
