# Generated by Django 4.2.11 on 2024-11-15 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0018_delete_datasheet'),
        ('estimator', '0016_alter_estimate_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='estimate',
        ),
        migrations.AlterModelOptions(
            name='estimate',
            options={'ordering': ['-due_date'], 'verbose_name': 'Estimate List', 'verbose_name_plural': 'Estimate Lists'},
        ),
        migrations.AlterModelOptions(
            name='estimatedetails',
            options={'verbose_name': 'Estimated Additional info', 'verbose_name_plural': 'Estimated Additional infos'},
        ),
        migrations.AlterModelOptions(
            name='estimateequipment',
            options={'verbose_name': 'Estimated Equipment List', 'verbose_name_plural': 'Estimated Equipment Lists'},
        ),
        migrations.AlterModelOptions(
            name='estimatehistory',
            options={'ordering': ['created_on'], 'verbose_name': 'Estimate History', 'verbose_name_plural': 'Estimate Histories'},
        ),
        migrations.AddField(
            model_name='estimate',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estimateequipment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='estimateequipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='11/15/2024', null=True),
        ),
        migrations.AlterField(
            model_name='estimateequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment'),
        ),
    ]
