# Generated by Django 2.2.3 on 2019-09-14 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0016_auto_20190913_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='validity',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='09/14/2019', null=True),
        ),
    ]
