# Generated by Django 2.2.3 on 2020-10-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0016_auto_20201004_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='10/13/2020', null=True),
        ),
        migrations.AlterField(
            model_name='estimatedetails',
            name='hours',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Regular Hours'), (5, 'Off Hours'), (10, 'Saturday/Holidays'), (15, 'Sunday')], default=0),
        ),
    ]
