# Generated by Django 2.2.3 on 2020-10-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0017_auto_20201013_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='10/14/2020', null=True),
        ),
    ]
