# Generated by Django 2.2.3 on 2019-09-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0017_auto_20190914_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='09/21/2019', null=True),
        ),
    ]
