# Generated by Django 4.2.11 on 2024-11-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_controlsystem_release_date_and_more'),
        ('estimator', '0017_remove_proposal_quote_remove_quote_estimate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proposal',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
