# Generated by Django 3.1.3 on 2020-12-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0018_auto_20201209_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateequipment',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
