# Generated by Django 2.2.3 on 2019-09-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0018_auto_20190921_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='09/23/2019', null=True),
        ),
    ]
