# Generated by Django 4.2.11 on 2024-12-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0018_delete_proposal_delete_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='12/08/2024', null=True),
        ),
    ]
