# Generated by Django 4.2.11 on 2024-12-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0019_alter_estimate_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
