# Generated by Django 3.1.3 on 2020-12-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0019_auto_20201209_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='12/14/2020', null=True),
        ),
    ]
