# Generated by Django 2.2.3 on 2019-10-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0019_auto_20190923_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='10/06/2019', null=True),
        ),
    ]
