# Generated by Django 2.2.3 on 2020-12-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0020_auto_20201214_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='12/28/2020', null=True),
        ),
    ]
