# Generated by Django 4.2.11 on 2024-12-28 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0020_alter_estimate_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatedetails',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='estimatedetails',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='estimatedetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estimateequipment',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='estimatehistory',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='estimatehistory',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='estimatehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estimatedetails',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estimateequipment',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estimatehistory',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
