# Generated by Django 2.2.3 on 2020-04-02 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimator', '0020_auto_20200331_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/02/2020', null=True),
        ),
        migrations.AlterField(
            model_name='estimateequipment',
            name='estimate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estimator.Estimate'),
        ),
    ]
