# Generated by Django 4.2.11 on 2025-01-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0003_alter_equipment_service'),
        ('estimator', '0021_estimatedetails_archive_estimatedetails_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimateequipment',
            options={},
        ),
        migrations.AlterField(
            model_name='estimateequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipment'),
        ),
    ]
