# Generated by Django 2.2.3 on 2020-04-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimator', '0021_auto_20200402_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/03/2020', null=True),
        ),
    ]
