# Generated by Django 2.2.3 on 2019-10-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0022_auto_20191015_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='10/17/2019', null=True),
        ),
    ]
