# Generated by Django 3.0.2 on 2020-04-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimator', '0022_auto_20200403_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/29/2020', null=True),
        ),
    ]
