# Generated by Django 3.0.2 on 2020-04-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimator', '0023_auto_20200429_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/30/2020', null=True),
        ),
    ]
