# Generated by Django 2.2.3 on 2019-10-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0023_auto_20191017_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='10/27/2019', null=True),
        ),
    ]
