# Generated by Django 2.2.3 on 2019-11-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0024_auto_20191027_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='note',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='note',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='note',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='11/02/2019', null=True),
        ),
    ]
