# Generated by Django 3.0.2 on 2020-05-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('estimator', '0024_auto_20200430_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='05/02/2020', null=True),
        ),
    ]
