# Generated by Django 2.2.3 on 2019-11-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0025_auto_20191102_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='11/09/2019', null=True),
        ),
    ]
