# Generated by Django 2.2.3 on 2019-11-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0026_auto_20191109_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='11/10/2019', null=True),
        ),
    ]
