# Generated by Django 2.2.3 on 2019-11-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0027_auto_20191110_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='11/11/2019', null=True),
        ),
    ]
