# Generated by Django 2.2.3 on 2019-11-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0028_auto_20191111_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='validity',
            field=models.IntegerField(default=30),
        ),
    ]
