# Generated by Django 2.2.3 on 2019-11-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0029_auto_20191111_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='11/29/2019', null=True),
        ),
    ]
