# Generated by Django 2.2.3 on 2019-11-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0030_auto_20191129_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='11/30/2019', null=True),
        ),
    ]
