# Generated by Django 2.2.3 on 2021-02-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0030_auto_20210222_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='02/23/2021', null=True),
        ),
    ]
