# Generated by Django 2.2.3 on 2019-12-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0031_auto_20191130_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='12/03/2019', null=True),
        ),
        migrations.AlterField(
            model_name='estimatedetails',
            name='pre_demo',
            field=models.FloatField(default=0),
        ),
    ]
