# Generated by Django 2.2.3 on 2019-12-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0032_auto_20191203_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='12/05/2019', null=True),
        ),
    ]
