# Generated by Django 2.2.3 on 2021-04-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0040_auto_20210401_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/04/2021', null=True),
        ),
    ]
