# Generated by Django 2.2.3 on 2021-04-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0042_auto_20210407_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/10/2021', null=True),
        ),
    ]
