# Generated by Django 2.2.3 on 2021-04-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0044_auto_20210412_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/14/2021', null=True),
        ),
    ]
