# Generated by Django 2.2.3 on 2021-04-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0045_auto_20210414_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/15/2021', null=True),
        ),
    ]
