# Generated by Django 2.2.3 on 2021-04-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0047_auto_20210416_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
