# Generated by Django 2.2.3 on 2021-04-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0050_auto_20210419_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/20/2021', null=True),
        ),
    ]
