# Generated by Django 2.2.3 on 2021-04-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0052_auto_20210422_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/23/2021', null=True),
        ),
    ]
