# Generated by Django 2.2.3 on 2021-04-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0053_auto_20210423_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/24/2021', null=True),
        ),
        migrations.AlterField(
            model_name='estimatedetails',
            name='control_system',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1%'), (2, '2%'), (3, '3%'), (4, '4%'), (5, '5%')], default=0),
        ),
    ]
