# Generated by Django 2.2.3 on 2021-04-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0054_auto_20210424_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatedetails',
            name='customer_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
