# Generated by Django 2.2.3 on 2021-04-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0055_estimatedetails_customer_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedetails',
            name='customer_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
