# Generated by Django 2.2.3 on 2021-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0056_auto_20210424_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/28/2021', null=True),
        ),
    ]
