# Generated by Django 2.2.3 on 2021-07-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0069_auto_20210603_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='07/23/2021', null=True),
        ),
        migrations.AlterField(
            model_name='estimatedetails',
            name='customer_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
