# Generated by Django 2.2.3 on 2021-07-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0071_auto_20210728_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='07/29/2021', null=True),
        ),
    ]
