# Generated by Django 2.2.3 on 2021-07-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0075_auto_20210706_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='07/12/2021', null=True),
        ),
    ]
