# Generated by Django 3.1.5 on 2021-07-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0077_auto_20210713_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='07/18/2021', null=True),
        ),
        migrations.AlterField(
            model_name='estimatedetails',
            name='customer_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
