# Generated by Django 2.2.3 on 2021-08-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0077_auto_20210817_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='08/28/2021', null=True),
        ),
    ]
