# Generated by Django 2.2.3 on 2022-04-29 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0083_auto_20220319_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/29/2022', null=True),
        ),
        migrations.CreateModel(
            name='EstimateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('pdf_filename', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimator.Estimate')),
            ],
            options={
                'verbose_name': 'Estimate History',
                'verbose_name_plural': 'Estimate History',
                'ordering': ['-created_on'],
            },
        ),
    ]
