# Generated by Django 4.0.4 on 2022-04-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0083_auto_20220319_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/17/2022', null=True),
        ),
    ]
