# Generated by Django 4.0.4 on 2022-04-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0088_alter_estimate_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateequipment',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
