# Generated by Django 3.2.13 on 2022-04-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0084_auto_20220429_1045'),
        ('estimator', '0089_alter_estimateequipment_quantity'),
    ]

    operations = [
    ]
