# Generated by Django 3.2.13 on 2022-04-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0090_merge_20220429_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatehistory',
            name='pdf_filename',
        ),
        migrations.AddField(
            model_name='estimatehistory',
            name='version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
