# Generated by Django 3.2.13 on 2022-05-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0091_auto_20220429_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimatehistory',
            options={'ordering': ['created_on'], 'verbose_name': 'Estimate History', 'verbose_name_plural': 'Estimate History'},
        ),
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='05/03/2022', null=True),
        ),
    ]
