# Generated by Django 3.1.14 on 2022-05-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0092_auto_20220503_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='05/22/2022', null=True),
        ),
    ]
