# Generated by Django 4.2.6 on 2024-04-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0097_alter_estimate_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='04/29/2024', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='validity',
            field=models.IntegerField(default=180),
        ),
    ]
