# Generated by Django 4.2.6 on 2024-05-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0098_alter_estimate_due_date_alter_proposal_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.DateField(default='05/11/2024', null=True),
        ),
    ]
