# Generated by Django 4.2.6 on 2024-05-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheetcreator', '0114_auto_20220522_1203'),
        ('dbmanagement', '0019_auto_20210723_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitotTraverseEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_data_entry_completed', models.BooleanField(default=False)),
                ('actual_data_entry_completed', models.BooleanField(default=False)),
                ('field_order', models.PositiveIntegerField(default=0)),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipment')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.datasheet')),
            ],
            options={
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='PitotTraverseSheetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.PositiveSmallIntegerField(choices=[(1, 'Design'), (2, 'Actual')], default=1)),
                ('value', models.CharField(max_length=500)),
                ('pitot_traverse_summary_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsheetpitottraverse.pitottraverseequipment')),
                ('sheet_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheetfield')),
            ],
        ),
    ]
