# Generated by Django 2.2.3 on 2021-08-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetprimaryheatexchanger2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primaryheatexchanger2equipment',
            name='equipment',
        ),
    ]
