# Generated by Django 2.2.3 on 2021-08-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetprimaryheatexchanger2', '0002_remove_primaryheatexchanger2equipment_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryheatexchanger2equipment',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='primaryheatexchanger2equipment',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
