# Generated by Django 2.2.3 on 2020-10-24 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SettledOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settled_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settlement.Settlement')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
