# Generated by Django 5.1.6 on 2025-03-30 06:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('settlement_start', models.DateTimeField(null=True)),
                ('settlement_end', models.DateTimeField(null=True)),
                ('fixed_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_contractor', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SettledSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('settled_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('settled_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('settled_type', models.BooleanField(default=False)),
                ('settled_hours', models.FloatField(default=0)),
                ('previous_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('settle_override', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('completion_percentage', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('schedule', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.schedule')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settlement.settlement')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SettledMaintenances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('settled_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('settled_hours', models.FloatField(default=0)),
                ('maintenance', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.maintenance')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settlement.settlement')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
