# Generated by Django 2.2.3 on 2020-04-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settledorders',
            name='settled_value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
