# Generated by Django 2.2.3 on 2020-04-03 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('settlement', '0002_auto_20200402_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settledorders',
            name='order',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
