# Generated by Django 2.2.3 on 2021-04-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0003_settledorders_completion_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settledorders',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
