# Generated by Django 2.2.3 on 2020-04-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('settlement', '0003_auto_20200403_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='settledorders',
            name='order_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
