# Generated by Django 2.2.3 on 2021-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0004_auto_20210410_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='settledorders',
            name='settled_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settledorders',
            name='settled_type',
            field=models.BooleanField(default=False),
        ),
    ]
