# Generated by Django 2.2.3 on 2020-04-03 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('settlement', '0004_settledorders_order_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settledorders',
            name='order_value',
        ),
    ]
