# Generated by Django 2.2.3 on 2021-04-12 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0005_auto_20210412_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='settledorders',
            name='contractor_involvement_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
