# Generated by Django 2.2.3 on 2021-04-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0006_settledorders_contractor_involvement_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='settlement_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='settlement_start',
            field=models.DateTimeField(null=True),
        ),
    ]
