# Generated by Django 2.2.3 on 2021-04-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0008_settlement_fixed_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='fixed_expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
