# Generated by Django 2.2.3 on 2021-04-17 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_auto_20210417_1209'),
        ('settlement', '0009_auto_20210414_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettledMaintenances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settled_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('settled_hours', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('maintenance', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Maintenance')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settlement.Settlement')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
