# Generated by Django 2.2.3 on 2021-04-17 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0052_auto_20210417_1209'),
        ('settlement', '0010_settledmaintenances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settledmaintenances',
            name='maintenance',
        ),
        migrations.AddField(
            model_name='settledmaintenances',
            name='order',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
            preserve_default=False,
        ),
    ]
