# Generated by Django 2.2.3 on 2021-04-22 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0011_auto_20210417_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_contractor', to=settings.AUTH_USER_MODEL),
        ),
    ]
