# Generated by Django 2.2.3 on 2021-04-22 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_auto_20210422_2015'),
        ('settlement', '0012_auto_20210422_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SettledOrders',
            new_name='SettledSchedule',
        ),
        migrations.RemoveField(
            model_name='settledmaintenances',
            name='order',
        ),
        migrations.RemoveField(
            model_name='settledschedule',
            name='order',
        ),
        migrations.AddField(
            model_name='settledmaintenances',
            name='schedule',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Schedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settledschedule',
            name='schedule',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Schedule'),
            preserve_default=False,
        ),
    ]
