# Generated by Django 2.2.3 on 2021-04-22 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_auto_20210422_2015'),
        ('settlement', '0013_auto_20210422_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settledmaintenances',
            name='schedule',
        ),
        migrations.AddField(
            model_name='settledmaintenances',
            name='maintenance',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Maintenance'),
            preserve_default=False,
        ),
    ]
