# Generated by Django 2.2.3 on 2021-04-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0014_auto_20210422_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settledschedule',
            name='contractor_involvement_percentage',
        ),
    ]
