# Generated by Django 2.2.3 on 2021-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0015_remove_settledschedule_contractor_involvement_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settledschedule',
            name='settled_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
