# Generated by Django 2.2.3 on 2021-04-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0016_settledschedule_settled_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='settledschedule',
            name='previous_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
