# Generated by Django 2.2.3 on 2021-05-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0017_settledschedule_previous_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settledschedule',
            name='completion_percentage',
        ),
    ]
