# Generated by Django 2.2.3 on 2021-05-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0018_remove_settledschedule_completion_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='settledschedule',
            name='settle_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='settledmaintenances',
            name='settled_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='settledschedule',
            name='settled_hours',
            field=models.FloatField(default=0),
        ),
    ]
