# Generated by Django 2.2.3 on 2021-05-06 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0019_auto_20210505_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='settledschedule',
            name='completion_percentage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
