from django.urls import path

from .views import (
    OrderListAPIView,
    OrderAddAPIView,
    OrderEditAPIView,
    OrderDeleteAPIView,
    OrderArchiveAPIView,
    ChangeOrderCreateApiView,
    ChangeOrderDeleteAPIView,
    ChangeOrderApproveView,
    ControlSystemAPIView,
    OrderEquipmentSubmittalView,
    OrderFieldDrawingView,
    OrderGeneralNotesView,
    OrderSitePicturesView,
    OrderFullUpdateAPIView,
    OrderProposalListView,
    ControlSystemListCreateView,
    ControlSystemDetailView,
    ControlSystemManufacturerListCreateView,
    ControlSystemManufacturerDetailView,
    # TechLabelRetrieveUpdateView,
    TechLabelDeleteView,
    # TechLabelListCreateView,
)


urlpatterns = [
    path('orders/',
         OrderListAPIView.as_view(),
         name='order-list'),  # List orders
    path('orders/proposals/',
         OrderProposalListView.as_view(),
         name='order-proposal-list'),
    path('orders/proposals/<int:proposal_id>/',
         OrderProposalListView.as_view(),
         name='order-proposal-by-proposal_id'),
    path('orders/add/',
         OrderAddAPIView.as_view()
         , name='order-add'),  # Add a new order
    path('orders/edit/<int:order_id>/',
         OrderEditAPIView.as_view(),
         name='order-edit'),  # Edit an existing order
    path('orders/delete/<int:order_id>/',
         OrderDeleteAPIView.as_view(),
         name='order-delete'),  # Delete an order
    path('orders/archive/<int:order_id>/',
         OrderArchiveAPIView.as_view(),
         name='order-archive'),  # Archive an order
    path('orders/change-orders/<int:order_id>/',
         ChangeOrderCreateApiView.as_view(),
         name='change-order-create'),  # Create a change order
    path('orders/change-orders/<int:order_id>/delete/<int:change_order_id>/',
         ChangeOrderDeleteAPIView.as_view(),
         name='change-order-delete'),
    path('orders/change-orders/<int:change_order_id>/approve/<str:action>/',
         ChangeOrderApproveView.as_view(),
         name='change-order-approve'),
    path('orders/<int:order_id>/control-system/',
         ControlSystemAPIView.as_view(),
         name='control-system'),  # Handle control system for an order
    path('orders/<int:order_id>/equipment-submittal/',
         OrderEquipmentSubmittalView.as_view(),
         name='order_equipment_submittal'),
    path('orders/<int:order_id>/field-drawing/',
         OrderFieldDrawingView.as_view(),
         name='order-field-drawing'),
    path('orders/<int:order_id>/general-notes/',
         OrderGeneralNotesView.as_view(),
         name='order-general-notes'),
    path('orders/<int:order_id>/site-pictures/',
         OrderSitePicturesView.as_view(),
         name='order-site-pictures'),
    path('orders/<int:order_id>/update/',
         OrderFullUpdateAPIView.as_view(),
         name='order-full-update'),
    path('orders/control-systems/',
         ControlSystemListCreateView.as_view(),
         name='control-system-list'),
    path('orders/control-systems/<int:pk>/',
         ControlSystemDetailView.as_view(),
         name='control-system-detail'),
    path('orders/control-systems/manufacturer/',
         ControlSystemManufacturerListCreateView.as_view(),
         name='control-system-manufacturer-list'),
    path('orders/control-systems/manufacturer/<int:pk>/',
         ControlSystemManufacturerDetailView.as_view(),
         name='control-system-manufacturer-detail'),
    # path('orders/techlabels/',
    #      TechLabelListCreateView.as_view(),
    #      name='techlabel-list-create'),
    # path('orders/techlabels/<int:pk>/',
    #      TechLabelRetrieveUpdateView.as_view(),
    #      name='techlabel-detail'),
    path('orders/techlabels/<int:pk>/',
         TechLabelDeleteView.as_view(),
         name='techlabel-delete'),
]
