from django.urls import path

from .views import (
    OrderListAPIView,
    OrderAddAPIView,
    OrderEditAPIView,
    OrderDeleteAPIView,
    OrderArchiveAPIView,
    ChangeOrderApiView,
    ChangeOrderDeleteAPIView,
    ChangeOrderApproveView,
    ControlSystemAPIView,
    OrderEquipmentSubmittalView,
    OrderFieldDrawingView,
    OrderGeneralNotesView,
    OrderSitePicturesView,
    OrderFullUpdateAPIView,
    OrderProposalListView,
    ControlSystemListCreateView,
    ControlSystemDetailView,
    ControlSystemManufacturerListCreateView,
    ControlSystemManufacturerDetailView,
    TechLabelDeleteView,
    TechLabelListView,
    TechLabelCreateUpdateView,
    TechLabelByOrderView,
    ChangeOrderList,
)


urlpatterns = [
    path("", OrderListAPIView.as_view(), name="order-list"),
    path(
        "proposals/",
        OrderProposalListView.as_view(),
        name="order-proposal-list",
    ),
    path(
        "proposals/<int:proposal_id>/",
        OrderProposalListView.as_view(),
        name="order-proposal-by-proposal_id",
    ),
    path("add/", OrderAddAPIView.as_view(), name="order-add"),
    path(
        "edit/<int:order_id>/", OrderEditAPIView.as_view(), name="order-edit"
    ),  # Edit an existing order
    path(
        "delete/<int:order_id>/",
        OrderDeleteAPIView.as_view(),
        name="order-delete",
    ),  # Delete an order
    path(
        "archive/<int:order_id>/",
        OrderArchiveAPIView.as_view(),
        name="order-archive",
    ),  # Archive an order
    path(
        "change-orders/<int:order_id>/",
        ChangeOrderList.as_view(),
        name="change-orders",
    ),
    path(
        "change-order/<int:order_id>/",
        ChangeOrderApiView.as_view(),
        name="change-order-create",
    ),
    path(
        "change-order/<int:change_order_id>/",
        ChangeOrderDeleteAPIView.as_view(),
        name="change-order-remove",
    ),
    path(
        "change-order/<int:change_order_id>/approve/",
        ChangeOrderApproveView.as_view(),
        name="change-order-approve",
    ),
    path(
        "<int:order_id>/control-system/",
        ControlSystemAPIView.as_view(),
        name="control-system",
    ),  # Handle control system for an order
    path(
        "<int:order_id>/equipment-submittal/",
        OrderEquipmentSubmittalView.as_view(),
        name="order_equipment_submittal",
    ),
    path(
        "<int:order_id>/field-drawing/",
        OrderFieldDrawingView.as_view(),
        name="order-field-drawing",
    ),
    path(
        "<int:order_id>/general-notes/",
        OrderGeneralNotesView.as_view(),
        name="order-general-notes",
    ),
    path(
        "<int:order_id>/site-pictures/",
        OrderSitePicturesView.as_view(),
        name="order-site-pictures",
    ),
    path(
        "<int:order_id>/update/",
        OrderFullUpdateAPIView.as_view(),
        name="order-full-update",
    ),
    path(
        "control-systems/",
        ControlSystemListCreateView.as_view(),
        name="control-system-list",
    ),
    path(
        "control-systems/<int:pk>/",
        ControlSystemDetailView.as_view(),
        name="control-system-detail",
    ),
    path(
        "control-systems/manufacturer/",
        ControlSystemManufacturerListCreateView.as_view(),
        name="control-system-manufacturer-list",
    ),
    path(
        "control-systems/manufacturer/<int:pk>/",
        ControlSystemManufacturerDetailView.as_view(),
        name="control-system-manufacturer-detail",
    ),
    path(
        "techlabels/",
        TechLabelListView.as_view(),
        name="techlabel-list",
    ),
    path(
        "techlabel/<int:order_id>/",
        TechLabelCreateUpdateView.as_view(),
        name="techlabel-create-update",
    ),
    path(
        "techlabel/<int:pk>/",
        TechLabelDeleteView.as_view(),
        name="techlabel-delete",
    ),
    path(
        "techlabel/<int:order_id>/detail/",
        TechLabelByOrderView.as_view(),
        name="techlabel-detail-by-order_id",
    ),
]
