"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i%06y2q&4l-!nv*8oolv470b!o)!xg*^9f7^d=q10#b$wd%c_e'

ENV = 'local'

# SECURITY WARNING: don't run with debug turned on in production!
if ENV == 'local':
    DEBUG = True
if ENV == 'production':
    DEBUG = False
if ENV == 'test':
    DEBUG = True

if ENV == 'local':
    ALLOWED_HOSTS = ['127.0.0.1']
if ENV == 'production':
    ALLOWED_HOSTS = ['dashboard.tabtechinc.com']
if ENV == 'test':
    ALLOWED_HOSTS = ['airtab.us', 'www.airtab.us']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_use_email_as_username.apps.DjangoUseEmailAsUsernameConfig',
    'custom_user.apps.CustomUserConfig',
    'djrichtextfield',
    'tinymce',
    'import_export',
    'rest_framework',
    'snowpenguin.django.recaptcha2',
    'django_select2',
    'adminsortable2',
    'mysite.core',
    'mysite.estimator',
    'mysite.submittal',
    'mysite.mgmreport',
    'mysite.order',
    'mysite.coi',
    'mysite.gi',
    'mysite.report',
    'mysite.bidfilemgm',
    'mysite.ibfm',
    'mysite.administrative',
    'mysite.schedule',
    'mysite.settlement',
    'mysite.dbmanagement',
    'mysite.sheetcreator',
    'mysite.testsheetvav',
    'mysite.testsheetterminal',
    'mysite.generatereport',
    'api',
    'django.contrib.humanize',
    'mysite.estimator.templatetags',
    'mysite.pdf_analyzer'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'mysite/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

if ENV == 'local':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

if ENV == 'production':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'dtabtech_maindb',
            'USER': 'dtabtech_dtab',
            'PASSWORD': 'UzP^e&9pXEK,',
            'HOST': 'localhost',
        }
    }

if ENV == 'test':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'airtab_dbnew2',
            'USER': 'airtab_usr',
            'PASSWORD': 'GKY%ZZyd@p=v',
            'HOST': 'localhost',
        }
    }

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

if ENV == 'local':
    TIME_ZONE = 'Asia/Tehran'
if ENV == 'production':
    TIME_ZONE = 'America/New_York'
if ENV == 'test':
    TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

if ENV == 'local':
    STATIC_URL = '/static/'
if ENV == 'production':
    STATIC_URL = '/dashboard/static/'
if ENV == 'test':
    STATIC_URL = '/python/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

if ENV == 'local':
    MEDIA_URL = '/media/'
if ENV == 'production':
    MEDIA_URL = '/dashboard/media/'
if ENV == 'test':
    MEDIA_URL = '/python/media/'
MEDIA_URL_NOSLASH = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

if ENV == 'local':
    UPLOAD_URL = '/uploads/'
if ENV == 'production':
    UPLOAD_URL = '/uploads/'
if ENV == 'test':
    UPLOAD_URL = '/uploads/'

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

if ENV == 'local':
    EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
    EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'sent_emails')
if ENV == 'production':
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_USE_SSL = True
    EMAIL_HOST = 'mail.tabtechinc.com'
    EMAIL_HOST_USER = 'contactus@tabtechinc.com'
    EMAIL_HOST_PASSWORD = 'J8]FrgW#OY8b'
    EMAIL_PORT = 465
if ENV == 'test':
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_USE_SSL = True
    EMAIL_HOST = 'mail.tabtechinc.com'
    EMAIL_HOST_USER = 'estimator2@tabtechinc.com'
    EMAIL_HOST_PASSWORD = '7V]{vni6+~&M'
    EMAIL_PORT = 465

AUTH_USER_MODEL = 'custom_user.User'

DATE_INPUT_FORMATS = ['%m/%d/%Y']

if ENV == 'local':
    WEB_URL = 'http://127.0.0.1:8000'
if ENV == 'production':
    WEB_URL = 'https://dashboard.tabtechinc.com'
if ENV == 'test':
    WEB_URL = 'https://airtab.us'

DJRICHTEXTFIELD_CONFIG = {
    'js': ['//tinymce.cachefly.net/4.1/tinymce.min.js'],
    'init_template': 'djrichtextfield/init/tinymce.js',
    'settings': {
        'menubar': True,
        'plugins': 'link image code',
        'toolbar': 'code | bold italic | link image | removeformat',
        'width': 700
    }
}

FILE_UPLOAD_PERMISSIONS = 0o644
MAX_UPLOAD_SIZE = 262144000
DEFAULT_FROM_EMAIL = 'Estimator at TAB <estimator@tabtechinc.com>'

BOOTSTRAP4 = {
    'include_jquery': True,
}

RECAPTCHA_PRIVATE_KEY = '6Levt-YUAAAAAClOFMj-oIofEeszrY4CMcQERlZj'
RECAPTCHA_PUBLIC_KEY = '6Levt-YUAAAAAEtQg-rc4Y9FqatZuPEdDeR4mDCk'

TINYMCE_SPELLCHECKER = False
TINYMCE_COMPRESSOR = True
