# Generated by Django 2.2.3 on 2021-05-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbmanagement', '0017_auto_20210116_1214'),
        ('sheetcreator', '0076_auto_20210518_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=20, null=True)),
                ('model_number', models.CharField(blank=True, max_length=20, null=True)),
                ('main_data_entry_completed', models.BooleanField(default=False)),
                ('design_data_entry_completed', models.BooleanField(default=False)),
                ('actual_data_entry_completed', models.BooleanField(default=False)),
                ('field_order', models.PositiveIntegerField(default=0)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.Equipment')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.DataSheet')),
            ],
            options={
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='FlowSheetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('flow_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsheetflow.FlowEquipment')),
                ('sheet_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheetField')),
            ],
        ),
    ]
