# Generated by Django 2.2.3 on 2021-05-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowequipment',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.Equipment'),
        ),
    ]
