# Generated by Django 2.2.3 on 2021-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetflow', '0002_auto_20210518_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowsheetdata',
            name='value',
            field=models.CharField(max_length=500),
        ),
    ]
