# Generated by Django 2.2.3 on 2021-05-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetflow', '0003_auto_20210518_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowequipment',
            name='br_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
