# Generated by Django 2.2.3 on 2021-07-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetflow', '0004_flowequipment_br_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowsheetdata',
            name='data_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Design'), (2, 'Actual')], default=1),
        ),
    ]
