# Generated by Django 2.2.3 on 2021-08-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetflow', '0005_flowsheetdata_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowequipment',
            name='equipment_group',
            field=models.CharField(default='A', max_length=50),
        ),
    ]
