# Generated by Django 2.2.3 on 2021-08-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0019_auto_20210723_1021'),
        ('testsheetvavboxschedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vbsequipment',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.EquipmentDb'),
        ),
        migrations.AddField(
            model_name='vbsequipment',
            name='main_data_entry_completed',
            field=models.BooleanField(default=False),
        ),
    ]
