# Generated by Django 2.2.3 on 2020-03-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='03/03/2020'),
        ),
    ]
