# Generated by Django 2.2.3 on 2020-10-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='10/25/2020'),
        ),
    ]
