# Generated by Django 2.2.3 on 2020-03-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0002_auto_20200303_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='03/05/2020'),
        ),
    ]
