# Generated by Django 2.2.3 on 2020-10-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20201026_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='10/31/2020'),
        ),
    ]
