# Generated by Django 2.2.3 on 2020-11-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20201107_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='11/11/2020'),
        ),
    ]
