# Generated by Django 3.0.2 on 2020-09-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20200915_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='09/19/2020'),
        ),
    ]
