# Generated by Django 4.2.11 on 2024-07-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_report_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='07/08/2024'),
        ),
    ]
