# Generated by Django 3.0.2 on 2020-09-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20200926_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='09/27/2020'),
        ),
    ]
