# Generated by Django 2.2.3 on 2020-09-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20200928_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='09/29/2020'),
        ),
    ]
