# Generated by Django 3.0.2 on 2020-05-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('report', '0014_auto_20200430_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='05/02/2020'),
        ),
    ]
