# Generated by Django 4.2.11 on 2024-12-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_alter_report_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(),
        ),
    ]
