# Generated by Django 2.2.3 on 2021-01-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_auto_20210116_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='01/25/2021'),
        ),
    ]
