# Generated by Django 2.2.3 on 2021-02-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0028_auto_20210216_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='02/22/2021'),
        ),
    ]
