# Generated by Django 2.2.3 on 2021-04-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0049_auto_20210420_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='04/22/2021'),
        ),
    ]
