# Generated by Django 2.2.3 on 2021-05-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0062_auto_20210528_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='05/29/2021'),
        ),
    ]
