# Generated by Django 2.2.3 on 2021-07-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0066_auto_20210723_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='07/28/2021'),
        ),
    ]
