# Generated by Django 3.2 on 2021-08-13 12:29

from django.db import migrations, models
import mysite.report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0072_auto_20210810_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=mysite.report.models.Report._),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='08/13/2021'),
        ),
    ]
