# Generated by Django 2.2.3 on 2021-08-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0073_auto_20210813_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='08/17/2021'),
        ),
    ]
