# Generated by Django 2.2.3 on 2021-09-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0075_auto_20210828_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='09/11/2021'),
        ),
    ]
