# Generated by Django 2.2.3 on 2022-03-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0079_auto_20211116_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='03/19/2022'),
        ),
    ]
