# Generated by Django 3.2.13 on 2022-04-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0081_auto_20220429_1045'),
        ('report', '0085_alter_report_report_date'),
    ]

    operations = [
    ]
