# Generated by Django 3.2.13 on 2023-07-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0088_auto_20220522_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='07/05/2023'),
        ),
    ]
