# Generated by Django 3.2.13 on 2023-09-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0090_alter_report_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='09/13/2023'),
        ),
    ]
