# Generated by Django 4.2.6 on 2024-05-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0093_alter_report_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='05/11/2024'),
        ),
    ]
