# Generated by Django 3.0.2 on 2020-05-28 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySubmittal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('archive', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Person')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Project')),
            ],
            options={
                'verbose_name': 'Company Submittal',
                'verbose_name_plural': 'Company Submittal',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SubmittalForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('flag', models.BooleanField(default=True)),
                ('submittal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submittal.CompanySubmittal')),
                ('submittal_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CompanySubmittalForm')),
            ],
            options={
                'verbose_name': 'Submittal Links to Forms',
                'verbose_name_plural': 'Submittal Links to Forms',
            },
        ),
    ]
