# Generated by Django 2.2.3 on 2019-12-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submittal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittalforms',
            name='submittal_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.CompanySubmittalForm'),
        ),
    ]
