# Generated by Django 2.2.3 on 2021-07-23 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbmanagement', '0019_auto_20210723_1021'),
        ('sheetcreator', '0093_auto_20210723_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirMovingEquipmentEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_no', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('area_served', models.CharField(blank=True, max_length=30, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=20, null=True)),
                ('main_data_entry_completed', models.BooleanField(default=False)),
                ('design_data_entry_completed', models.BooleanField(default=False)),
                ('actual_data_entry_completed', models.BooleanField(default=False)),
                ('field_order', models.PositiveIntegerField(default=0)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.EquipmentDb')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.Equipment')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.DataSheet')),
            ],
            options={
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='AirMovingEquipmentSheetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.PositiveSmallIntegerField(choices=[(1, 'Design'), (2, 'Actual')], default=1)),
                ('value', models.CharField(max_length=500)),
                ('air_moving_equipment_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsheetairmovingequipment.AirMovingEquipmentEquipment')),
                ('sheet_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheetField')),
            ],
        ),
    ]
