# Generated by Django 4.0.4 on 2022-04-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetsetup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airmovingequipmentsheetdata',
            name='air_moving_equipment_equipment',
        ),
        migrations.RemoveField(
            model_name='airmovingequipmentsheetdata',
            name='sheet_field',
        ),
        migrations.DeleteModel(
            name='AirMovingEquipmentEquipment',
        ),
        migrations.DeleteModel(
            name='AirMovingEquipmentSheetData',
        ),
    ]
