# Generated by Django 2.2.3 on 2021-10-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsheethotwaterboiler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotwaterboilersheetdata',
            old_name='pump_equipment',
            new_name='hot_water_boiler_equipment',
        ),
    ]
