# Generated by Django 4.2.11 on 2024-05-11 07:33

import creditcards.models
import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCheckingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_account', models.CharField(max_length=50)),
                ('bank_routing_number', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('account_number', models.CharField(max_length=17, validators=[django.core.validators.MinLengthValidator(17)])),
                ('business_tax_id', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='CompanySubmittalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(blank=True, max_length=255)),
                ('form_file', models.FileField(upload_to='uploads/submittalforms')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company Submittal Forms',
                'verbose_name_plural': 'Company Submittal Forms',
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Type',
                'verbose_name_plural': 'Company Type',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(error_messages={'required': 'Name Required.'}, max_length=255)),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('mail', models.EmailField(blank=True, max_length=55)),
                ('web', models.CharField(blank=True, max_length=55)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=55)),
                ('state', models.CharField(blank=True, max_length=55)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('customer_adjustment_in_percentage', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company Contact info',
                'verbose_name_plural': 'Company Contact info',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_nickname', models.CharField(max_length=50)),
                ('name_on_the_card', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('card_expiration_date', creditcards.models.CardExpiryField()),
                ('default_card', models.BooleanField(default=False)),
                ('billing_address_line_1', models.CharField(max_length=255, null=True)),
                ('billing_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_city', models.CharField(max_length=55, null=True)),
                ('billing_state', models.CharField(max_length=55, null=True)),
                ('billing_zip', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailBodyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', tinymce.models.HTMLField(blank=True, help_text='<b>Current User Information:</b><br />[user_name]: Logged in user Name | [user_title]: Logged in user Title | [user_cel]: Logged in user Cellphone Number | [user_tel]: Logged in user Telephone Number<br /><b>Customer Information:</b><br />[customer_company_name]: Customer Company Name | [customer_contact_person]: Customer Contact Person | [customer_email]: Customer Email | [customer_address_line_1]: Customer Address 2 | [customer_address_line_2]: Customer Address 1 | [customer_city]: Customer City | [customer_state]: Customer State | [customer_zip]: Customer Zip<br /><b>Insurance Company Information:</b><br />[ic_company_name]: Insurance Company Name | [ic_contact_name]: Insurance Company Contact Name | [ic_mail]: Insurance Company Email | [ic_tel]: Insurance Company Telephone | [ic_fax]: Insurance Company Fax | [ic_web]: Insurance Company Website | [ic_address_line_1]: Insurance Company Address 1 | [ic_address_line_2]: Insurance Company Address 2 | [ic_city]: Insurance Company City | [ic_state]: Insurance Company State | [ic_zip]: Insurance Company Zip', null=True)),
            ],
            options={
                'verbose_name': 'Email Body Template',
                'verbose_name_plural': 'Email Body Template',
            },
        ),
        migrations.CreateModel(
            name='LicenseFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'License Information Files',
                'verbose_name_plural': 'License Information Files',
            },
        ),
        migrations.CreateModel(
            name='LicenseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'License Information',
                'verbose_name_plural': 'License Information',
            },
        ),
        migrations.CreateModel(
            name='ModulesToEmailTemplateRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.PositiveSmallIntegerField(choices=[(1, 'Estimate'), (2, 'Quotation'), (3, 'Proposal'), (4, 'Invoice'), (5, 'Email Footer'), (6, 'COI'), (7, 'Submittal'), (8, 'Settlement'), (9, 'Account Summary')], unique=True)),
            ],
            options={
                'verbose_name': 'Connect Modules to Email Templates',
                'verbose_name_plural': 'Connect Modules to Email Templates',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1)),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('mail', models.EmailField(blank=True, max_length=55)),
                ('web', models.CharField(blank=True, max_length=55)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Contact Person',
                'verbose_name_plural': 'Company Contact Person',
                'ordering': ('company',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('emp_id', models.CharField(blank=True, max_length=10, null=True)),
                ('tel', models.CharField(blank=True, max_length=30, null=True)),
                ('fax', models.CharField(blank=True, max_length=30, null=True)),
                ('cell', models.CharField(blank=True, max_length=30, null=True)),
                ('e_sign', models.FileField(blank=True, null=True, upload_to='uploads/users/signs')),
                ('pic', models.FileField(blank=True, null=True, upload_to='uploads/users/profiles')),
                ('wallpaper', models.FileField(blank=True, null=True, upload_to='uploads/users/wallpapers')),
                ('stamp', models.FileField(blank=True, null=True, upload_to='uploads/users/stamps')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'customer'), (2, 'super admin'), (3, 'estimator'), (4, 'accounting'), (5, 'tech'), (6, 'super tech')], default=1)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Employee'), (2, 'Contractor')], null=True)),
                ('id_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('interest_percentage', models.PositiveIntegerField(default=0, help_text='exclusive for sub contractors.', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='exclusive for sub contractors.', max_digits=8, null=True)),
                ('physical_address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_city', models.CharField(blank=True, max_length=55, null=True)),
                ('physical_state', models.CharField(blank=True, max_length=55, null=True)),
                ('physical_zip', models.CharField(blank=True, max_length=10, null=True)),
                ('billing_address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=55, null=True)),
                ('billing_state', models.CharField(blank=True, max_length=55, null=True)),
                ('billing_zip', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='(/ : ?) characters are not allowed on project name', max_length=255)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=55)),
                ('state', models.CharField(blank=True, max_length=55)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('mail', models.EmailField(blank=True, max_length=55)),
                ('note', models.TextField(blank=True, max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project Info',
                'verbose_name_plural': 'Project Info',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Services Offered',
                'verbose_name_plural': 'Services Offered',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='TechLabelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('model_no', models.CharField(max_length=50, unique=True)),
                ('size', models.CharField(max_length=50, unique=True, verbose_name='Size (in)')),
            ],
        ),
    ]
