# Generated by Django 3.1.3 on 2020-12-09 11:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbodytemplate',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='<b>Current User Information:</b><br />[user_name]: Logged in user Name | [user_title]: Logged in user Title | [user_cel]: Logged in user Cellphone Number | [user_tel]: Logged in user Telephone Number<br /><b>Customer Information:</b><br />[customer_company_name]: Customer Company Name | [customer_contact_person]: Customer Contact Person | [customer_email]: Customer Email | [customer_address_line_1]: Customer Address 2 | [customer_address_line_2]: Customer Address 1 | [customer_city]: Customer City | [customer_state]: Customer State | [customer_zip]: Customer Zip<br /><b>Insurance Company Information:</b><br />[ic_company_name]: Insurance Company Name | [ic_contact_name]: Insurance Company Contact Name | [ic_mail]: Insurance Company Email | [ic_tel]: Insurance Company Telephone | [ic_fax]: Insurance Company Fax | [ic_web]: Insurance Company Website | [ic_address_line_1]: Insurance Company Address 1 | [ic_address_line_2]: Insurance Company Address 2 | [ic_city]: Insurance Company City | [ic_state]: Insurance Company State | [ic_zip]: Insurance Company Zip', null=True),
        ),
    ]
