# Generated by Django 2.2.3 on 2019-12-20 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ContactInfo'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulestoemailtemplaterelation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.EmailBodyTemplate'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Service'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='test_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.TestSheet'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='company_type',
            field=models.ForeignKey(error_messages={'required': 'You have to specify Company Type.'}, on_delete=django.db.models.deletion.CASCADE, to='core.CompanyType'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companysubmittalform',
            name='related_services',
            field=models.ManyToManyField(to='core.Service'),
        ),
    ]
