# Generated by Django 3.1.3 on 2020-12-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201209_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulestoemailtemplaterelation',
            name='module',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Estimate'), (2, 'Quotation'), (3, 'Proposal'), (4, 'Invoice'), (5, 'Email Footer'), (6, 'COI'), (7, 'Submittal'), (8, 'Settlement'), (9, 'Account Summary')], unique=True),
        ),
    ]
