# Generated by Django 3.0.2 on 2020-06-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200528_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheet',
            name='sheet_generator',
            field=models.BooleanField(default=False),
        ),
    ]
