# Generated by Django 4.2.11 on 2024-11-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytype',
            options={'ordering': ('name',), 'verbose_name': 'Company Type', 'verbose_name_plural': 'Company Types'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('company',), 'verbose_name': 'Company Contact Person', 'verbose_name_plural': 'Company Contact Persons'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',), 'verbose_name': 'Project Info', 'verbose_name_plural': 'Projects Info'},
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Super Admin'), (1, 'Estimator'), (2, 'Accounting'), (3, 'Super Tech'), (4, 'Tech'), (5, 'Customer')], default=5),
        ),
    ]
