# Generated by Django 2.2.3 on 2019-09-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190706_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cell',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='e_sign',
            field=models.FileField(blank=True, null=True, upload_to='uploads/users/signs'),
        ),
        migrations.AddField(
            model_name='profile',
            name='emp_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fax',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='uploads/users/profiles'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stamp',
            field=models.FileField(blank=True, null=True, upload_to='uploads/users/stamps'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallpaper',
            field=models.FileField(blank=True, null=True, upload_to='uploads/users/wallpapers'),
        ),
    ]
