# Generated by Django 2.2.3 on 2021-02-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201209_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='customer_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
