# Generated by Django 2.2.3 on 2019-10-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190921_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseinfo',
            name='key',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
