# Generated by Django 3.0.2 on 2020-09-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testsheet_sheet_generator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechLabelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('model_no', models.CharField(max_length=50, unique=True)),
                ('size', models.CharField(max_length=50, unique=True, verbose_name='Size (in)')),
            ],
        ),
    ]
