# Generated by Django 2.2.3 on 2021-04-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactinfo_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fixed_monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='exclusive for sub contractors.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='exclusive for sub contractors.', max_digits=8, null=True),
        ),
    ]
