# Generated by Django 2.2.3 on 2019-10-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191015_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensefiles',
            name='key',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
