# Generated by Django 2.2.3 on 2020-02-11 07:00

import creditcards.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20200211_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCheckingAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_account', models.CharField(max_length=50)),
                ('bank_routing_number', models.CharField(max_length=9)),
                ('account_number', models.CharField(max_length=17)),
                ('business_tax_id', models.CharField(max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_card', models.CharField(max_length=50)),
                ('card_number', creditcards.models.CardNumberField(max_length=25)),
                ('card_expiration_date', creditcards.models.CardExpiryField()),
                ('default_card', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='AddressInfo',
        ),
    ]
