# Generated by Django 2.2.3 on 2020-02-11 07:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_auto_20200211_1030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessCheckingAccounts',
            new_name='BusinessCheckingAccount',
        ),
        migrations.RenameModel(
            old_name='CreditCards',
            new_name='CreditCard',
        ),
    ]
