# Generated by Django 2.2.3 on 2021-04-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210404_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='fixed_monthly_payment',
        ),
    ]
