# Generated by Django 2.2.3 on 2019-10-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191015_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='estimate_work',
            field=models.IntegerField(default=10),
        ),
    ]
