# Generated by Django 2.2.3 on 2019-10-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_equipment_estimate_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='estimate_work',
            field=models.IntegerField(default=10, verbose_name='Estimate Work in Minutes'),
        ),
    ]
