# Generated by Django 2.2.3 on 2020-02-11 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_auto_20200211_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscheckingaccount',
            name='account_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.MinLengthValidator(17)]),
        ),
        migrations.AlterField(
            model_name='businesscheckingaccount',
            name='bank_routing_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
        migrations.AlterField(
            model_name='businesscheckingaccount',
            name='business_tax_id',
            field=models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
