# Generated by Django 2.2.3 on 2021-04-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_person_fixed_monthly_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
