# Generated by Django 2.2.3 on 2019-11-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191027_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBodyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('template', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Email Body Template',
                'verbose_name_plural': 'Email Body Template',
            },
        ),
    ]
