# Generated by Django 2.2.3 on 2020-03-01 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_auto_20200211_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.IntegerField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
