# Generated by Django 2.2.3 on 2021-04-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_person_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_tech', to='core.Person'),
        ),
    ]
