# Generated by Django 2.2.3 on 2021-04-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'customer'), (2, 'super admin'), (3, 'estimator'), (4, 'accounting'), (5, 'tech'), (6, 'super tech'), (7, 'contractor')], default=1),
        ),
    ]
