# Generated by Django 2.2.3 on 2019-11-09 18:01

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emailbodytemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailbodytemplate',
            name='template',
        ),
        migrations.AddField(
            model_name='emailbodytemplate',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
