# Generated by Django 2.2.3 on 2019-11-09 18:03

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191109_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbodytemplate',
            name='content',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
