# Generated by Django 2.2.3 on 2020-03-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_auto_20200301_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='billing_address_line_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='billing_address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='billing_city',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='billing_state',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='billing_zip',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='billing_address_line_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='billing_city',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='billing_state',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='billing_zip',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='physical_address_line_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='physical_city',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='physical_state',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='physical_zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
