# Generated by Django 2.2.3 on 2020-03-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200301_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='name_of_card',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_nickname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='name_on_the_card',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
