# Generated by Django 2.2.3 on 2021-04-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210420_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Employee'), (2, 'Contractor')], null=True),
        ),
    ]
