# Generated by Django 2.2.3 on 2019-11-10 16:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191109_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbodytemplate',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
