# Generated by Django 2.2.3 on 2019-11-10 16:43

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191110_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbodytemplate',
            name='content',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
