# Generated by Django 2.2.3 on 2021-04-22 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='interest_percentage',
        ),
        migrations.RemoveField(
            model_name='person',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='profile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='exclusive for sub contractors.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest_percentage',
            field=models.PositiveIntegerField(default=0, help_text='exclusive for sub contractors.', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
