# Generated by Django 2.2.3 on 2020-04-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_auto_20200301_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'customer'), (2, 'super admin'), (3, 'estimator'), (4, 'accounting'), (5, 'tech'),
                         (6, 'super tech')], default=1),
        ),
    ]
