# Generated by Django 2.2.3 on 2019-11-11 14:07

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191110_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbodytemplate',
            name='content',
            field=djrichtextfield.models.RichTextField(blank=True, help_text='reza', null=True),
        ),
    ]
