# Generated by Django 2.2.3 on 2020-04-03 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200403_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='interest_percentage',
            field=models.PositiveIntegerField(default=0, help_text='exclusive for sub contractors.', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
