# Generated by Django 2.2.3 on 2021-04-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210422_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='customer_adjustment',
            field=models.FloatField(default=0),
        ),
    ]
