# Generated by Django 2.2.3 on 2021-04-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contactinfo_customer_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='customer_adjustment',
            field=models.IntegerField(default=0),
        ),
    ]
