# Generated by Django 2.2.3 on 2019-11-11 14:42

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191111_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbodytemplate',
            name='content',
            field=djrichtextfield.models.RichTextField(blank=True, help_text='[user_name]: Logged in user Name | [user_title]: Logged in user Title | [user_cel]: Logged in user Cellphone Number | [user_tel]: Logged in user Telephone Number', null=True),
        ),
        migrations.CreateModel(
            name='ModulesToEmailTemplateRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.EmailBodyTemplate')),
            ],
            options={
                'verbose_name': 'Connect Modules to Email Templates',
                'verbose_name_plural': 'Connect Modules to Email Templates',
            },
        ),
    ]
