# Generated by Django 2.2.3 on 2020-04-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_contactinfo_interest_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulestoemailtemplaterelation',
            name='module',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Estimate'), (2, 'Quotation'), (3, 'Proposal'), (4, 'Invoice'), (5, 'Email Footer'),
                         (6, 'COI'), (7, 'Submittal'), (8, 'Settlement')], unique=True),
        ),
    ]
