# Generated by Django 2.2.3 on 2021-04-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210424_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='customer_adjustment',
            new_name='customer_adjustment_in_percentage',
        ),
    ]
