# Generated by Django 3.0.2 on 2020-04-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_auto_20200403_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name': 'Types of Equipment',
                     'verbose_name_plural': 'Types of Equipment'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='billing_address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='billing_city',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='billing_state',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='billing_zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='profile_customer', to='core.Person'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='physical_address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='physical_city',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='physical_state',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='physical_zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='EquipmentDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipment')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   to='core.EquipmentManufacturer')),
            ],
            options={
                'verbose_name': 'Equipment Database',
                'verbose_name_plural': 'Equipment Database',
            },
        ),
    ]
