# Generated by Django 2.2.3 on 2019-11-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191111_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulestoemailtemplaterelation',
            name='template',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.EmailBodyTemplate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modulestoemailtemplaterelation',
            name='module',
            field=models.CharField(max_length=30),
        ),
    ]
