# Generated by Django 2.2.3 on 2021-04-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210424_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
