# Generated by Django 3.0.2 on 2020-04-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_auto_20200429_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmanufacturer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
