# Generated by Django 2.2.3 on 2019-11-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191111_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulestoemailtemplaterelation',
            name='module',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Estimate'), (2, 'Quotation'), (3, 'Proposal'), (4, 'Invoice'), (5, 'Email Footer')], unique=True),
        ),
    ]
