# Generated by Django 2.2.3 on 2021-06-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210428_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='(/ : ?) characters are not allowed on project name', max_length=255),
        ),
    ]
