# Generated by Django 3.0.2 on 2020-04-30 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0017_equipmentcustomfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcustomfield',
            name='equipment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Equipment'),
            preserve_default=False,
        ),
    ]
