# Generated by Django 2.2.3 on 2019-11-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191111_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulestoemailtemplaterelation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.EmailBodyTemplate'),
        ),
    ]
