# Generated by Django 3.0.2 on 2020-04-30 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0018_equipmentcustomfield_equipment_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipmentCustomField',
        ),
    ]
