# Generated by Django 3.0.2 on 2020-04-30 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0019_delete_equipmentcustomfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_value_name', models.CharField(max_length=255)),
                ('company_value', models.CharField(max_length=50)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EquipmentDb')),
            ],
        ),
    ]
