# Generated by Django 2.2.3 on 2019-11-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='street',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='street',
            new_name='address_line_1',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='licensefiles',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='licenseinfo',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
