# Generated by Django 2.2.3 on 2019-11-30 18:42

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20191129_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbodytemplate',
            name='content',
            field=djrichtextfield.models.RichTextField(blank=True, help_text='[user_name]: Logged in user Name | [user_title]: Logged in user Title | [user_cel]: Logged in user Cellphone Number | [user_tel]: Logged in user Telephone Number | <br />[ic_company_name]: Insurance Company Name | [ic_contact_name]: Insurance Company Contact Name | [ic_mail]: Insurance Company Name | [ic_tel]: Insurance Company Name | [ic_fax]: Insurance Company Name | [ic_web]: Insurance Company Name | [ic_address_line_1]: Insurance Company Name | ', null=True),
        ),
    ]
