# Generated by Django 3.0.2 on 2020-05-02 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0020_equipmentcustomfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name': 'Equipment Type', 'verbose_name_plural': 'Equipment Type'},
        ),
        migrations.AlterField(
            model_name='equipmentcustomfield',
            name='company_value',
            field=models.CharField(max_length=50, verbose_name='Design Value'),
        ),
        migrations.AlterField(
            model_name='equipmentcustomfield',
            name='equipment_value_name',
            field=models.CharField(max_length=255, verbose_name='Field Name'),
        ),
        migrations.CreateModel(
            name='EquipmentTypeCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255, verbose_name='Field Name')),
                ('field_type', models.PositiveSmallIntegerField(
                    choices=[(1, 'Integer ex: 1, 2, 3, ...'), (2, 'Float ex: 1.2, 52.75, ...'),
                             (3, 'Characters ex: mechanical, water based, ...')], default=1)),
                ('field_range', models.CharField(max_length=50, verbose_name='Field Range if Integer or Float')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipment')),
            ],
        ),
    ]
