# Generated by Django 3.0.2 on 2020-05-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200502_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttypecustomfield',
            name='field_postfix',
            field=models.CharField(blank=True, max_length=20, verbose_name='Postfix ex: RPM, V, ...'),
        ),
    ]
