# Generated by Django 2.2.3 on 2019-12-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20191130_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Test Sheet',
                'verbose_name_plural': 'Test Sheet',
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='test_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.TestSheet'),
        ),
    ]
