# Generated by Django 3.0.2 on 2020-05-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_equipmenttypecustomfield_field_postfix'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttypecustomfield',
            name='field_range_or_selective',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Range ex: 150-720'), (2, 'Selective ex: 1,2,3')], default=1),
        ),
    ]
