# Generated by Django 3.0.2 on 2020-05-03 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_equipmenttypecustomfield_field_range_or_selective'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTypeCustomOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255)),
                ('operand_type', models.PositiveSmallIntegerField(choices=[(1, 'Equal to'), (2, 'Greater than'), (3, 'Smaller than')], default=1)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Equipment')),
                ('result_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EquipmentTypeCustomField')),
            ],
        ),
    ]
