# Generated by Django 3.0.2 on 2020-05-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_equipmenttypecustomoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttypecustomoperation',
            name='result_field',
            field=models.CharField(max_length=50),
        ),
    ]
