# Generated by Django 3.0.2 on 2020-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200503_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmanufacturer',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipmentmanufacturer',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='equipmentmanufacturer',
            name='city',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='equipmentmanufacturer',
            name='fax',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='equipmentmanufacturer',
            name='mail',
            field=models.EmailField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='equipmentmanufacturer',
            name='state',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='equipmentmanufacturer',
            name='tel',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='equipmentmanufacturer',
            name='web',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='equipmentmanufacturer',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
