# Generated by Django 3.0.2 on 2020-05-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200503_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttypecustomfield',
            name='default_value',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
