# Generated by Django 3.0.2 on 2020-05-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_equipmenttypecustomfield_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttypecustomoperation',
            name='operand_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Equal to'), (2, 'Greater than'), (3, 'Greater or Equal to'), (4, 'Smaller than'), (5, 'Smaller or Equal to')], default=1),
        ),
    ]
