# Generated by Django 3.0.2 on 2020-05-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimate_work', models.IntegerField(default=10, verbose_name='Estimate Work in Minutes')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Service')),
                ('test_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.TestSheet')),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('mail', models.EmailField(blank=True, max_length=55)),
                ('web', models.CharField(blank=True, max_length=55)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=55)),
                ('state', models.CharField(blank=True, max_length=55)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTypeCustomOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255)),
                ('operand_type', models.PositiveSmallIntegerField(choices=[(1, 'Equal to'), (2, 'Greater than'), (3, 'Greater or Equal to'), (4, 'Smaller than'), (5, 'Smaller or Equal to')], default=1)),
                ('result_field', models.CharField(max_length=50)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTypeCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255, verbose_name='Field Name')),
                ('field_type', models.PositiveSmallIntegerField(choices=[(1, 'Integer ex: 1, 2, 3, ...'), (2, 'Float ex: 1.2, 52.75, ...'), (3, 'Characters ex: mechanical, water based, ...')], default=1)),
                ('field_range_or_selective', models.PositiveSmallIntegerField(choices=[(1, 'Range ex: 150-720'), (2, 'Selective ex: 1,2,3')], default=1)),
                ('field_range', models.CharField(blank=True, max_length=50, verbose_name='Field Range if Integer or Float')),
                ('field_postfix', models.CharField(blank=True, max_length=20, verbose_name='Postfix ex: RPM, V, ...')),
                ('default_value', models.CharField(blank=True, max_length=50)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.Equipment')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbmanagement.EquipmentManufacturer')),
            ],
            options={
                'verbose_name': 'Equipment Database',
                'verbose_name_plural': 'Equipment Database',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_value_name', models.CharField(max_length=255, verbose_name='Field Name')),
                ('company_value', models.CharField(max_length=50, verbose_name='Design Value')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.EquipmentDb')),
            ],
        ),
    ]
