# Generated by Django 4.2.11 on 2024-05-11 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirTerminalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('default', models.CharField(blank=True, max_length=10)),
                ('size_type', models.PositiveSmallIntegerField(choices=[(1, 'Size in One Field (inch)'), (2, 'Size in Two Field (x*y)')], default=2, verbose_name='No. of Size Fields')),
                ('is_custom', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'RGDs',
                'verbose_name_plural': 'RGDs',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimate_work', models.IntegerField(default=10, verbose_name='Estimate Work in Minutes')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment_submittal', models.FileField(blank=True, null=True, upload_to='uploads/equipmentDb/equipment_submittal')),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/equipmentDb/image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipment')),
            ],
            options={
                'verbose_name': 'Equipment Database',
                'verbose_name_plural': 'Equipment Database',
            },
        ),
        migrations.CreateModel(
            name='EquipmentManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('mail', models.EmailField(blank=True, max_length=55)),
                ('web', models.CharField(blank=True, max_length=55)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=55)),
                ('state', models.CharField(blank=True, max_length=55)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('sheet_generator', models.BooleanField(default=False)),
                ('flag', models.BooleanField(default=True)),
                ('inheritance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheet')),
            ],
            options={
                'verbose_name': 'Test Sheet',
                'verbose_name_plural': 'Test Sheet',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='TestSheetOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255, verbose_name='ex: [field-1-design] + [field-2-actual]')),
                ('operand_type', models.PositiveSmallIntegerField(choices=[(1, 'Equal to'), (2, 'Greater than'), (3, 'Greater or Equal to'), (4, 'Smaller than'), (5, 'Smaller or Equal to'), (6, 'Assign to')], default=1)),
                ('result_field', models.CharField(max_length=50, verbose_name='ex: [field-3-design]')),
                ('apply_on_design', models.BooleanField(default=True)),
                ('apply_on_actual', models.BooleanField(default=True)),
                ('field_order', models.PositiveIntegerField(default=0)),
                ('test_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheet')),
            ],
            options={
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='TestSheetField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255, verbose_name='Field Name')),
                ('field_type', models.PositiveSmallIntegerField(choices=[(1, 'Integer ex: 1, 2, 3, ...'), (2, 'Float ex: 1.2, 52.75, ...'), (3, 'Characters ex: mechanical, water based, ...'), (4, 'Selectable Yes or No')], default=1)),
                ('field_range_or_selective', models.PositiveSmallIntegerField(choices=[(1, 'Range ex: 150-720'), (2, 'Selective ex: 1,2,3')], default=1)),
                ('field_range', models.CharField(blank=True, max_length=50, verbose_name='Field Range or Field Selection')),
                ('field_postfix', models.CharField(blank=True, max_length=20, verbose_name='Postfix ex: RPM, V, ...')),
                ('default_value', models.CharField(blank=True, max_length=50)),
                ('show_parentheses', models.PositiveSmallIntegerField(choices=[(1, 'None'), (2, 'In Design Value'), (3, 'In Actual Value'), (4, 'In Both Cases')], default=1)),
                ('show_in_design', models.BooleanField(default=True)),
                ('required_in_design', models.BooleanField(default=False)),
                ('show_in_actual', models.BooleanField(default=True)),
                ('required_in_actual', models.BooleanField(default=False)),
                ('field_order', models.PositiveIntegerField(default=0)),
                ('test_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheet')),
            ],
            options={
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='TestSheetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_title', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('test_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheet')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTypeCustomOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255)),
                ('operand_type', models.PositiveSmallIntegerField(choices=[(1, 'Equal to'), (2, 'Greater than'), (3, 'Greater or Equal to'), (4, 'Smaller than'), (5, 'Smaller or Equal to'), (6, 'Assign to')], default=1)),
                ('result_field', models.CharField(max_length=50)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTypeCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255, verbose_name='Field Name')),
                ('field_type', models.PositiveSmallIntegerField(choices=[(1, 'Integer ex: 1, 2, 3, ...'), (2, 'Float ex: 1.2, 52.75, ...'), (3, 'Characters ex: mechanical, water based, ...'), (4, 'Selectable Yes or No')], default=1)),
                ('field_range_or_selective', models.PositiveSmallIntegerField(choices=[(1, 'Range ex: 150-720'), (2, 'Selective ex: 1,2,3')], default=1)),
                ('field_range', models.CharField(blank=True, max_length=50, verbose_name='Field Range if Integer or Float')),
                ('field_postfix', models.CharField(blank=True, max_length=20, verbose_name='Postfix ex: RPM, V, ...')),
                ('default_value', models.CharField(blank=True, max_length=50)),
                ('show_parentheses', models.PositiveSmallIntegerField(choices=[(1, 'None'), (2, 'In Design Value'), (3, 'In Actual Value'), (4, 'In Both Cases')], default=1)),
                ('required_in_design', models.BooleanField(default=False)),
                ('required_in_actual', models.BooleanField(default=False)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentDbDesignData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipmentdb')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheetfield')),
            ],
        ),
        migrations.AddField(
            model_name='equipmentdb',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbmanagement.equipmentmanufacturer'),
        ),
        migrations.CreateModel(
            name='EquipmentCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_value_name', models.CharField(max_length=255, verbose_name='Field Name')),
                ('company_value', models.CharField(max_length=50, verbose_name='Design Value')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipmentdb')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='test_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbmanagement.testsheet'),
        ),
        migrations.CreateModel(
            name='ActualDataCustomOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255)),
                ('operand_type', models.PositiveSmallIntegerField(choices=[(1, 'Equal to'), (2, 'Greater than'), (3, 'Greater or Equal to'), (4, 'Smaller than'), (5, 'Smaller or Equal to'), (6, 'Assign to')], default=1)),
                ('result_field', models.CharField(max_length=50)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipment')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='equipmentdb',
            unique_together={('manufacturer', 'model_number')},
        ),
    ]
