# Generated by Django 2.2.3 on 2020-10-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsheetfield',
            name='field_name',
            field=models.CharField(max_length=255, verbose_name='Field Name'),
        ),
    ]
