# Generated by Django 4.2.11 on 2024-06-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdb',
            name='actual_data_entry_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipmentdb',
            name='design_data_entry_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipmentdb',
            name='main_data_entry_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
