# Generated by Django 4.2.11 on 2025-01-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_address_options_and_more'),
        ('dbmanagement', '0002_equipmentdb_actual_data_entry_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_equipments', to='core.service'),
        ),
    ]
