# Generated by Django 3.0.2 on 2020-06-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0002_auto_20200530_2058'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentdb',
            unique_together={('manufacturer', 'model_number')},
        ),
    ]
