# Generated by Django 2.2.3 on 2020-10-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0002_auto_20201024_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSheetOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255, verbose_name='ex: [field-1-design] + [field-2-actual]')),
                ('operand_type', models.PositiveSmallIntegerField(choices=[(1, 'Equal to'), (2, 'Greater than'), (3, 'Greater or Equal to'), (4, 'Smaller than'), (5, 'Smaller or Equal to'), (6, 'Assign to')], default=1)),
                ('result_field', models.CharField(max_length=50, verbose_name='ex: [field-3-design]')),
                ('test_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheet')),
            ],
        ),
    ]
