# Generated by Django 3.0.2 on 2020-07-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0003_auto_20200608_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcustomfield',
            name='actual_value_necessity',
            field=models.BooleanField(default=False),
        ),
    ]
