# Generated by Django 2.2.3 on 2020-10-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0003_testsheetoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheetfield',
            name='show_in_actual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testsheetfield',
            name='show_in_design',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testsheetoperation',
            name='check_in_actual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testsheetoperation',
            name='check_in_design',
            field=models.BooleanField(default=True),
        ),
    ]
