# Generated by Django 2.2.3 on 2020-08-28 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0003_auto_20200608_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttypecustomfield',
            name='show_parentheses',
            field=models.PositiveSmallIntegerField(choices=[(1, 'None'), (2, 'In Design Value'), (3, 'In Actual Value'), (4, 'In Both Cases')], default=1),
        ),
        migrations.AlterField(
            model_name='equipmenttypecustomoperation',
            name='operand_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Equal to'), (2, 'Greater than'), (3, 'Greater or Equal to'), (4, 'Smaller than'), (5, 'Smaller or Equal to'), (6, 'Assign to')], default=1),
        ),
        migrations.CreateModel(
            name='ActualDataCustomOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=255)),
                ('operand_type', models.PositiveSmallIntegerField(choices=[(1, 'Equal to'), (2, 'Greater than'), (3, 'Greater or Equal to'), (4, 'Smaller than'), (5, 'Smaller or Equal to'), (6, 'Assign to')], default=1)),
                ('result_field', models.CharField(max_length=50)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.Equipment')),
            ],
        ),
    ]
