# Generated by Django 3.0.2 on 2020-07-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0004_equipmentcustomfield_actual_value_necessity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentcustomfield',
            name='actual_value_necessity',
        ),
    ]
