# Generated by Django 2.2.3 on 2020-10-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0004_auto_20201024_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsheetoperation',
            old_name='check_in_actual',
            new_name='apply_on_actual',
        ),
        migrations.RenameField(
            model_name='testsheetoperation',
            old_name='check_in_design',
            new_name='apply_on_design',
        ),
        migrations.AlterField(
            model_name='testsheetfield',
            name='field_range',
            field=models.CharField(blank=True, max_length=50, verbose_name='Field Range or Field Selection'),
        ),
    ]
