# Generated by Django 2.2.3 on 2020-10-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0005_auto_20201024_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdb',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbmanagement.EquipmentManufacturer'),
        ),
        migrations.AlterField(
            model_name='equipmentdb',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
