# Generated by Django 3.0.2 on 2020-07-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0005_remove_equipmentcustomfield_actual_value_necessity'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttypecustomfield',
            name='field_actual_value_necessity',
            field=models.BooleanField(default=False),
        ),
    ]
