# Generated by Django 2.2.3 on 2020-10-24 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0006_auto_20201024_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSheetColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_title', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('test_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheet')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentDbDesignData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.EquipmentDb')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheetColumn')),
            ],
        ),
    ]
