# Generated by Django 3.0.2 on 2020-07-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0006_equipmenttypecustomfield_field_actual_value_necessity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttypecustomfield',
            name='field_actual_value_necessity',
        ),
    ]
