# Generated by Django 2.2.3 on 2020-10-24 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0007_equipmentdbdesigndata_testsheetcolumn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdbdesigndata',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheetField'),
        ),
    ]
