# Generated by Django 3.0.2 on 2020-09-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0004_auto_20200828_1538'),
        ('dbmanagement', '0007_remove_equipmenttypecustomfield_field_actual_value_necessity'),
    ]

    operations = [
    ]
