# Generated by Django 3.0.2 on 2020-09-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0008_merge_20200909_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdb',
            name='serial_number',
        ),
    ]
