# Generated by Django 2.2.3 on 2020-11-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0009_testsheet_inheritance'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheetfield',
            name='field_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
