# Generated by Django 2.2.3 on 2020-09-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0009_remove_equipmentdb_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttypecustomfield',
            name='required_in_actual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipmenttypecustomfield',
            name='required_in_design',
            field=models.BooleanField(default=False),
        ),
    ]
