# Generated by Django 2.2.3 on 2020-11-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0010_testsheetfield_field_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsheetfield',
            options={'ordering': ['field_order']},
        ),
        migrations.AlterModelOptions(
            name='testsheetoperation',
            options={'ordering': ['field_order']},
        ),
        migrations.AddField(
            model_name='testsheetoperation',
            name='field_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
