# Generated by Django 2.2.3 on 2020-10-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0010_auto_20200929_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdb',
            name='equipment_submittal',
            field=models.FileField(blank=True, null=True, upload_to='uploads/equipmentDb_equipment_submittal'),
        ),
        migrations.AddField(
            model_name='equipmentdb',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/equipmentDb_image'),
        ),
    ]
