# Generated by Django 2.2.3 on 2020-10-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0011_auto_20201001_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdb',
            name='equipment_submittal',
            field=models.FileField(blank=True, null=True, upload_to='uploads/equipmentDb/equipment_submittal'),
        ),
        migrations.AlterField(
            model_name='equipmentdb',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/equipmentDb/image'),
        ),
    ]
