# Generated by Django 3.1.3 on 2020-11-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0011_auto_20201107_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirTerminalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('default', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'RGDs',
                'verbose_name_plural': 'RGDs',
            },
        ),
    ]
