# Generated by Django 3.1.3 on 2020-11-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0012_airterminalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airterminalcode',
            name='default',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
