# Generated by Django 2.2.3 on 2021-01-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0014_auto_20201209_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='airterminalcode',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
