# Generated by Django 2.2.3 on 2021-01-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0015_airterminalcode_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='airterminalcode',
            name='size_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Size in One Field (inch)'), (2, 'Size in Two Field (x*y)')], default=1, verbose_name='No. of Size Fields'),
        ),
    ]
