# Generated by Django 2.2.3 on 2021-01-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0016_airterminalcode_size_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airterminalcode',
            name='size_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Size in One Field (inch)'), (2, 'Size in Two Field (x*y)')], default=2, verbose_name='No. of Size Fields'),
        ),
    ]
