# Generated by Django 2.2.3 on 2021-06-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0017_auto_20210116_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsheet',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
