# Generated by Django 2.2.3 on 2021-07-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0018_auto_20210601_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airterminalcode',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='equipmenttypecustomfield',
            name='field_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Integer ex: 1, 2, 3, ...'), (2, 'Float ex: 1.2, 52.75, ...'), (3, 'Characters ex: mechanical, water based, ...'), (4, 'Selectable Yes or No')], default=1),
        ),
        migrations.AlterField(
            model_name='testsheetfield',
            name='field_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Integer ex: 1, 2, 3, ...'), (2, 'Float ex: 1.2, 52.75, ...'), (3, 'Characters ex: mechanical, water based, ...'), (4, 'Selectable Yes or No')], default=1),
        ),
    ]
