# Generated by Django 4.2.11 on 2024-05-11 07:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_start', models.DateTimeField()),
                ('schedule_end', models.DateTimeField()),
                ('archive', models.BooleanField(default=False)),
                ('pre_demo', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'Schedule List',
                'verbose_name_plural': 'Schedule List',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('involvement_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('settlement', models.BooleanField(default=False)),
                ('tech_upload', models.FileField(blank=True, null=True, upload_to='uploads/techfiles')),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assigned_to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_employee', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.schedule')),
            ],
            options={
                'verbose_name': 'Schedule Technicians',
                'verbose_name_plural': 'Schedule Technicians',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_start', models.DateTimeField()),
                ('schedule_end', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('maintenance_type', models.PositiveSmallIntegerField(choices=[(1, 'Maintenance'), (2, 'Lost Time'), (3, 'Off/Vacation')], default=1)),
                ('archive', models.BooleanField(default=False)),
                ('settlement', models.BooleanField(default=False)),
                ('tech_upload', models.FileField(blank=True, null=True, upload_to='uploads/techfiles')),
                ('note', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assigned_to_contractor', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assigned_to_employee', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'Maintenance List',
                'verbose_name_plural': 'Maintenance List',
                'ordering': ['-created_on'],
            },
        ),
    ]
