# Generated by Django 5.1.6 on 2025-03-30 06:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('schedule_start', models.DateTimeField(help_text='The start time of the maintenance schedule.')),
                ('schedule_end', models.DateTimeField(help_text='The end time of the maintenance schedule.')),
                ('description', models.TextField(blank=True, help_text='A brief description of the maintenance task.', max_length=500)),
                ('maintenance_type', models.PositiveSmallIntegerField(choices=[(1, 'Maintenance'), (2, 'Lost Time'), (3, 'Off/Vacation')], default=1, help_text='The type of maintenance task.')),
                ('settlement', models.BooleanField(default=False, help_text='Indicates whether the task has been settled.')),
                ('tech_upload', models.FileField(blank=True, help_text='File upload related to the maintenance task.', null=True, upload_to='uploads/techfiles')),
                ('note', models.TextField(blank=True, help_text='Additional notes related to the maintenance task.', max_length=1000, null=True)),
                ('assigned_to_contractor', models.ForeignKey(blank=True, help_text='The contractor assigned to this maintenance task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assigned_to_contractor', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_employee', models.ForeignKey(blank=True, help_text='The employee assigned to this maintenance task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assigned_to_employee', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='The order associated with this maintenance activity.', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'Maintenance List',
                'verbose_name_plural': 'Maintenance List',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('schedule_start', models.DateTimeField(help_text='The start time of the schedule.')),
                ('schedule_end', models.DateTimeField(help_text='The end time of the schedule.')),
                ('pre_demo', models.BooleanField(default=False, help_text='Indicates whether the schedule is for a pre-demonstration.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='The order associated with this schedule.', on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'Schedule List',
                'verbose_name_plural': 'Schedule List',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('involvement_percentage', models.PositiveIntegerField(default=0, help_text='The percentage of involvement of the technician.', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('settlement', models.BooleanField(default=False, help_text='Indicates whether the task has been settled.')),
                ('tech_upload', models.FileField(blank=True, help_text="File upload related to the technician's task.", null=True, upload_to='uploads/techfiles')),
                ('note', models.TextField(blank=True, help_text="Additional notes related to the technician's task.", max_length=1000, null=True)),
                ('assigned_to_contractor', models.ForeignKey(blank=True, help_text='The contractor assigned to this schedule.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assigned_to_employee', models.ForeignKey(blank=True, help_text='The employee assigned to this schedule.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_employee', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(help_text='The schedule associated with this technician.', on_delete=django.db.models.deletion.CASCADE, to='scheduler.schedule')),
            ],
            options={
                'verbose_name': 'Schedule Technicians',
                'verbose_name_plural': 'Schedule Technicians',
                'ordering': ['-created_on'],
            },
        ),
    ]
