# Generated by Django 4.2.11 on 2024-12-28 14:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0021_alter_order_options_changeorder_archive_and_more'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scheduletech',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='scheduletech',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='scheduletech',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='assigned_to_contractor',
            field=models.ForeignKey(blank=True, help_text='The contractor assigned to this maintenance task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assigned_to_contractor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='assigned_to_employee',
            field=models.ForeignKey(blank=True, help_text='The employee assigned to this maintenance task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assigned_to_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of the maintenance task.', max_length=500),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Maintenance'), (2, 'Lost Time'), (3, 'Off/Vacation')], default=1, help_text='The type of maintenance task.'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='note',
            field=models.TextField(blank=True, help_text='Additional notes related to the maintenance task.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='order',
            field=models.ForeignKey(blank=True, help_text='The order associated with this maintenance activity.', null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='schedule_end',
            field=models.DateTimeField(help_text='The end time of the maintenance schedule.'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='schedule_start',
            field=models.DateTimeField(help_text='The start time of the maintenance schedule.'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='settlement',
            field=models.BooleanField(default=False, help_text='Indicates whether the task has been settled.'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='tech_upload',
            field=models.FileField(blank=True, help_text='File upload related to the maintenance task.', null=True, upload_to='uploads/techfiles'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='order',
            field=models.ForeignKey(help_text='The order associated with this schedule.', on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pre_demo',
            field=models.BooleanField(default=False, help_text='Indicates whether the schedule is for a pre-demonstration.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_end',
            field=models.DateTimeField(help_text='The end time of the schedule.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_start',
            field=models.DateTimeField(help_text='The start time of the schedule.'),
        ),
        migrations.AlterField(
            model_name='scheduletech',
            name='assigned_to_contractor',
            field=models.ForeignKey(blank=True, help_text='The contractor assigned to this schedule.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduletech',
            name='assigned_to_employee',
            field=models.ForeignKey(blank=True, help_text='The employee assigned to this schedule.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduletech',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='scheduletech',
            name='involvement_percentage',
            field=models.PositiveIntegerField(default=0, help_text='The percentage of involvement of the technician.', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='scheduletech',
            name='note',
            field=models.TextField(blank=True, help_text="Additional notes related to the technician's task.", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scheduletech',
            name='schedule',
            field=models.ForeignKey(help_text='The schedule associated with this technician.', on_delete=django.db.models.deletion.CASCADE, to='scheduler.schedule'),
        ),
        migrations.AlterField(
            model_name='scheduletech',
            name='settlement',
            field=models.BooleanField(default=False, help_text='Indicates whether the task has been settled.'),
        ),
        migrations.AlterField(
            model_name='scheduletech',
            name='tech_upload',
            field=models.FileField(blank=True, help_text="File upload related to the technician's task.", null=True, upload_to='uploads/techfiles'),
        ),
    ]
