# Generated by Django 2.2.3 on 2021-03-06 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactinfo_customer_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='assigned_to_contractor',
        ),
        migrations.AddField(
            model_name='schedule',
            name='assigned_to_contractor',
            field=models.ManyToManyField(blank=True, to='core.Person'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='assigned_to_employee',
        ),
        migrations.AddField(
            model_name='schedule',
            name='assigned_to_employee',
            field=models.ManyToManyField(blank=True, related_name='assigned_to_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
