# Generated by Django 5.1.6 on 2025-05-14 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='assigned_to_contractor',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='assigned_to_employee',
        ),
        migrations.RemoveField(
            model_name='scheduletech',
            name='assigned_to_contractor',
        ),
        migrations.RemoveField(
            model_name='scheduletech',
            name='assigned_to_employee',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The user assigned to this maintenance task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduletech',
            name='assigned_to',
            field=models.ForeignKey(default=1, help_text='User assigned to this schedule.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
