# Generated by Django 2.2.3 on 2021-03-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20210306_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', unique=True),
        ),
    ]
