# Generated by Django 5.1.6 on 2025-05-14 06:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_maintenance_assigned_to_contractor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletech',
            options={'ordering': ['-created_on'], 'verbose_name': 'Schedule Technician', 'verbose_name_plural': 'Schedule Technicians'},
        ),
        migrations.AlterUniqueTogether(
            name='scheduletech',
            unique_together={('schedule', 'assigned_to')},
        ),
    ]
