# Generated by Django 2.2.3 on 2021-03-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20210327_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
