# Generated by Django 2.2.3 on 2021-03-28 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_contactinfo_customer_id'),
        ('scheduler', '0004_auto_20210327_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='assigned_to_contractor',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='assigned_to_employee',
        ),
        migrations.CreateModel(
            name='ScheduleTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_contractor', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person')),
                ('assigned_to_employee', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_employee', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Schedule')),
            ],
            options={
                'verbose_name': 'Schedule Technicians',
                'verbose_name_plural': 'Schedule Technicians',
                'ordering': ['-created_on'],
            },
        ),
    ]
