# Generated by Django 2.2.3 on 2021-03-28 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20210328_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletech',
            name='assigned_to_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AlterField(
            model_name='scheduletech',
            name='assigned_to_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
