# Generated by Django 2.2.3 on 2021-03-29 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20210328_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletech',
            name='involvement_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
