# Generated by Django 2.2.3 on 2021-04-01 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_contactinfo_customer_id'),
        ('order', '0043_auto_20210401_2001'),
        ('scheduler', '0008_scheduletech_involvement_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_start', models.DateTimeField()),
                ('schedule_end', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=500)),
                ('archive', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assigned_to_contractor', to='core.Person')),
                ('assigned_to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assigned_to_employee', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'verbose_name': 'Maintenance List',
                'verbose_name_plural': 'Maintenance List',
                'ordering': ['-created_on'],
            },
        ),
    ]
