# Generated by Django 2.2.3 on 2021-04-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletech',
            name='settlement',
            field=models.BooleanField(default=False),
        ),
    ]
