# Generated by Django 2.2.3 on 2021-04-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_scheduletech_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletech',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
