# Generated by Django 2.2.3 on 2021-04-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_maintenance_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletech',
            name='tech_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/techfiles'),
        ),
    ]
