# Generated by Django 2.2.3 on 2021-04-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_scheduletech_tech_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='settlement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='tech_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/techfiles'),
        ),
    ]
