# Generated by Django 2.2.3 on 2021-04-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_auto_20210417_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='pre_demo',
            field=models.BooleanField(default=False),
        ),
    ]
