# Generated by Django 2.2.3 on 2021-04-22 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_schedule_pre_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='assigned_to_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assigned_to_contractor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduletech',
            name='assigned_to_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
