# Generated by Django 2.2.3 on 2021-06-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_auto_20210422_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Design'), (2, 'Actual')], default=1),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Maintenance'), (2, 'Lost Time'), (3, 'Off/Vacation')], default=1),
        ),
    ]
