# Generated by Django 2.2.3 on 2021-06-15 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_auto_20210615_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='user_type',
            new_name='maintenance_type',
        ),
    ]
