# Generated by Django 2.2.3 on 2021-06-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_auto_20210615_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='type',
        ),
    ]
