# Generated by Django 5.1.6 on 2025-03-30 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbmanagement', '0001_initial'),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sheet_date', models.DateField(null=True)),
                ('system', models.CharField(max_length=50)),
                ('archive', models.BooleanField(default=False)),
                ('rogue_design_data_entry_completed', models.BooleanField(default=False)),
                ('rogue_actual_data_entry_completed', models.BooleanField(default=False)),
                ('main_data_entry_confirmed', models.BooleanField(default=False)),
                ('design_data_entry_confirmed', models.BooleanField(default=False)),
                ('actual_data_entry_confirmed', models.BooleanField(default=False)),
                ('main_data_entry_completed', models.BooleanField(default=False)),
                ('design_data_entry_completed', models.BooleanField(default=False)),
                ('actual_data_entry_completed', models.BooleanField(default=False)),
                ('terminal_design_data_entry_completed', models.BooleanField(default=False)),
                ('terminal_actual_data_entry_completed', models.BooleanField(default=False)),
                ('form_fields', models.JSONField(blank=True, null=True)),
                ('info', models.JSONField(blank=True, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('equipment_submittal', models.FileField(blank=True, null=True, upload_to='uploads/equipmentDb/equipment_submittal')),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/equipmentDb/image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('equipment_group', models.CharField(default='A', max_length=50)),
                ('number_of_supply_air_terminal', models.SmallIntegerField(default=0)),
                ('number_of_return_air_terminal', models.SmallIntegerField(default=0)),
                ('number_of_outside_air_terminal', models.SmallIntegerField(default=0)),
                ('number_of_exhaust_air_terminal', models.SmallIntegerField(default=0)),
                ('code', models.CharField(blank=True, max_length=128, null=True)),
                ('_default', models.CharField(blank=True, max_length=10)),
                ('size_type', models.PositiveSmallIntegerField(default=2, verbose_name='No. of Size Fields')),
                ('is_custom', models.BooleanField(default=False)),
                ('outlet_no', models.SmallIntegerField(default=0)),
                ('_type', models.PositiveSmallIntegerField(default=1)),
                ('other_group', models.SmallIntegerField(blank=True, null=True)),
                ('fan_no', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('area_served', models.CharField(blank=True, max_length=30, null=True)),
                ('attach', models.FileField(blank=True, null=True, upload_to='uploads/equipments/attach')),
                ('attach_type', models.CharField(blank=True, max_length=128, null=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sheets', to='equipments.equipment')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sheets', to='dbmanagement.equipmentmanufacturer')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generatereport.datasheet')),
            ],
            options={
                'verbose_name': 'Data Sheet',
                'verbose_name_plural': 'Data Sheets',
            },
        ),
    ]
