# Generated by Django 4.2.11 on 2024-05-11 07:33

from django.db import migrations, models
import django.db.models.deletion
import mysite.generatereport.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default='05/11/2024')),
                ('last_report_date', models.DateField(blank=True, null=True)),
                ('cover_report_date', models.DateField(blank=True, null=True)),
                ('upload_table_of_content', models.FileField(blank=True, null=True, upload_to='uploads/table_of_contents', validators=[mysite.generatereport.validators.validate_file_extension])),
                ('upload_test_sheets', models.FileField(blank=True, null=True, upload_to='uploads/testsheet_reports', validators=[mysite.generatereport.validators.validate_file_extension])),
                ('upload_drawing_pdf', models.FileField(blank=True, null=True, upload_to='uploads/drawing_pdfs', validators=[mysite.generatereport.validators.validate_file_extension])),
                ('report_type', models.PositiveSmallIntegerField(choices=[(1, 'Automatic'), (2, 'Manual'), (3, 'Import')], default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
