# Generated by Django 3.1.3 on 2020-12-05 08:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0018_auto_20201205_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default='12/05/2020')),
                ('general_notes_and_comments', tinymce.models.HTMLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='ReportDrawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_file', models.FileField(upload_to='uploads/drawings')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('report_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generatereport.reportsheet')),
            ],
        ),
    ]
