# Generated by Django 3.1.3 on 2020-12-05 09:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='general_notes_and_comments',
            field=tinymce.models.HTMLField(default='The systems described here in this report are operating per design intent.'),
        ),
    ]
