# Generated by Django 4.2.11 on 2024-05-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='05/22/2024'),
        ),
    ]
