# Generated by Django 3.1.3 on 2020-12-06 09:14

from django.db import migrations, models
import mysite.generatereport.validators


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0002_auto_20201205_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdrawing',
            name='drawing_file',
            field=models.FileField(upload_to='uploads/drawings', validators=[mysite.generatereport.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='12/06/2020'),
        ),
    ]
