# Generated by Django 4.2.11 on 2024-06-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0002_alter_reportsheet_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='06/15/2024'),
        ),
    ]
