# Generated by Django 3.1.3 on 2020-12-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0004_auto_20201207_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='12/09/2020'),
        ),
    ]
