# Generated by Django 4.2.11 on 2024-06-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0004_alter_reportsheet_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='06/22/2024'),
        ),
    ]
