# Generated by Django 2.2.3 on 2021-01-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0008_auto_20210104_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='01/11/2021'),
        ),
    ]
