# Generated by Django 4.2.11 on 2024-07-28 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0012_alter_reportsheet_report_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportsheet',
            options={'ordering': ['-report_date', 'project']},
        ),
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 28, 12, 17, 45, 460535)),
        ),
    ]
