# Generated by Django 2.2.3 on 2021-01-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0012_auto_20210128_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='01/29/2021'),
        ),
    ]
