# Generated by Django 4.2.11 on 2024-08-20 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0013_alter_reportsheet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsheet',
            name='revised_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 20, 11, 55, 38, 828367)),
        ),
    ]
