# Generated by Django 2.2.3 on 2021-02-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0014_auto_20210201_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='02/16/2021'),
        ),
    ]
