# Generated by Django 4.2.11 on 2024-08-20 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0014_reportsheet_revised_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 20, 12, 25, 2, 64170)),
        ),
    ]
