# Generated by Django 4.2.11 on 2024-08-29 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0015_alter_reportsheet_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 8, 29, 12, 15, 42, 364268)),
        ),
    ]
