# Generated by Django 4.2.11 on 2024-10-03 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0016_alter_reportsheet_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 3, 19, 10, 3, 29361)),
        ),
    ]
