# Generated by Django 4.2.11 on 2024-10-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0018_alter_reportsheet_report_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportSheet',
        ),
    ]
