# Generated by Django 2.2.3 on 2021-03-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0021_auto_20210307_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='03/27/2021'),
        ),
    ]
