# Generated by Django 2.2.3 on 2021-03-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0022_auto_20210327_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='03/28/2021'),
        ),
    ]
