# Generated by Django 2.2.3 on 2021-03-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0023_auto_20210328_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='03/29/2021'),
        ),
    ]
