# Generated by Django 2.2.3 on 2021-03-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0024_auto_20210329_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='03/31/2021'),
        ),
    ]
