# Generated by Django 2.2.3 on 2021-04-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0025_auto_20210331_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='04/01/2021'),
        ),
    ]
