# Generated by Django 2.2.3 on 2021-04-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0029_auto_20210410_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='04/12/2021'),
        ),
    ]
