# Generated by Django 2.2.3 on 2021-04-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0030_auto_20210412_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='04/14/2021'),
        ),
    ]
