# Generated by Django 2.2.3 on 2021-04-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0033_auto_20210416_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='04/17/2021'),
        ),
    ]
