# Generated by Django 2.2.3 on 2021-04-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0034_auto_20210417_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsheet',
            name='upload_drawing_pdf',
            field=models.FileField(default=1, upload_to='uploads/drawing_pdfs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportsheet',
            name='general_notes_and_comments',
            field=models.TextField(default='The systems described here in this report are operating per design intent.'),
        ),
    ]
