# Generated by Django 2.2.3 on 2021-04-17 20:13

from django.db import migrations, models
import mysite.generatereport.validators


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0035_auto_20210417_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='upload_drawing_pdf',
            field=models.FileField(upload_to='uploads/drawing_pdfs', validators=[mysite.generatereport.validators.validate_file_extension]),
        ),
        migrations.DeleteModel(
            name='ReportDrawing',
        ),
    ]
