# Generated by Django 2.2.3 on 2021-04-18 21:43

from django.db import migrations, models
import mysite.generatereport.validators


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0036_auto_20210417_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsheet',
            name='upload_abbreviation_page_image',
            field=models.FileField(default=1, upload_to='uploads/page_images', validators=[mysite.generatereport.validators.validate_img_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportsheet',
            name='upload_instrumentation_page_image',
            field=models.FileField(default=1, upload_to='uploads/page_images', validators=[mysite.generatereport.validators.validate_img_extension]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportsheet',
            name='upload_test_sheets',
            field=models.FileField(default=1, upload_to='uploads/testsheet_reports', validators=[mysite.generatereport.validators.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='04/19/2021'),
        ),
    ]
