# Generated by Django 2.2.3 on 2021-04-19 06:42

from django.db import migrations, models
import mysite.generatereport.validators


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0037_auto_20210419_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsheet',
            name='upload_table_of_content_page_image',
            field=models.FileField(default=1, upload_to='uploads/page_images', validators=[mysite.generatereport.validators.validate_img_extension]),
            preserve_default=False,
        ),
    ]
