# Generated by Django 2.2.3 on 2021-04-19 07:06

from django.db import migrations, models
import mysite.generatereport.validators


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0038_reportsheet_upload_table_of_content_page_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsheet',
            name='upload_table_of_content_page_image',
        ),
        migrations.AddField(
            model_name='reportsheet',
            name='upload_table_of_content',
            field=models.FileField(default=1, upload_to='uploads/table_of_contents', validators=[mysite.generatereport.validators.validate_file_extension]),
            preserve_default=False,
        ),
    ]
