# Generated by Django 2.2.3 on 2021-04-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0039_auto_20210419_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsheet',
            name='upload_abbreviation_page_image',
        ),
        migrations.RemoveField(
            model_name='reportsheet',
            name='upload_instrumentation_page_image',
        ),
    ]
