# Generated by Django 2.2.3 on 2021-04-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0043_auto_20210423_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='04/24/2021'),
        ),
    ]
