# Generated by Django 2.2.3 on 2021-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0044_auto_20210424_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='04/28/2021'),
        ),
    ]
