# Generated by Django 2.2.3 on 2021-05-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0046_auto_20210504_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='05/05/2021'),
        ),
    ]
