# Generated by Django 2.2.3 on 2021-05-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0048_auto_20210506_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='05/10/2021'),
        ),
    ]
