# Generated by Django 2.2.3 on 2021-05-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0049_auto_20210510_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='05/11/2021'),
        ),
    ]
