# Generated by Django 2.2.3 on 2021-05-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0050_auto_20210511_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='05/18/2021'),
        ),
    ]
