# Generated by Django 2.2.3 on 2021-07-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0062_auto_20210624_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='07/06/2021'),
        ),
    ]
