# Generated by Django 2.2.3 on 2021-10-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0067_auto_20210911_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='10/05/2021'),
        ),
    ]
