# Generated by Django 4.0.4 on 2022-04-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0071_auto_20220319_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='04/17/2022'),
        ),
    ]
