# Generated by Django 4.0.4 on 2022-04-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0072_alter_reportsheet_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsheet',
            name='automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='04/18/2022'),
        ),
    ]
