# Generated by Django 4.0.4 on 2022-04-18 09:15

from django.db import migrations, models
import mysite.generatereport.validators


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0073_reportsheet_automatic_alter_reportsheet_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='upload_drawing_pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/drawing_pdfs', validators=[mysite.generatereport.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='reportsheet',
            name='upload_table_of_content',
            field=models.FileField(blank=True, null=True, upload_to='uploads/table_of_contents', validators=[mysite.generatereport.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='reportsheet',
            name='upload_test_sheets',
            field=models.FileField(blank=True, null=True, upload_to='uploads/testsheet_reports', validators=[mysite.generatereport.validators.validate_file_extension]),
        ),
    ]
