# Generated by Django 4.0.4 on 2022-04-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0074_alter_reportsheet_upload_drawing_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='04/21/2022'),
        ),
    ]
