# Generated by Django 4.0.4 on 2022-04-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0077_alter_reportsheet_report_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsheet',
            name='general_notes_and_comments',
        ),
    ]
