# Generated by Django 3.2.13 on 2022-04-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0072_auto_20220429_1045'),
        ('generatereport', '0078_remove_reportsheet_general_notes_and_comments'),
    ]

    operations = [
    ]
