# Generated by Django 3.2.13 on 2022-05-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0079_merge_20220429_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsheet',
            name='last_report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='05/03/2022'),
        ),
    ]
