# Generated by Django 3.2.13 on 2022-05-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0081_auto_20220503_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Automatic'), (2, 'Manual'), (3, 'Import')], default=1),
        ),
    ]
