# Generated by Django 3.1.14 on 2022-05-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0082_alter_reportsheet_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheet',
            name='report_date',
            field=models.DateField(default='05/22/2022'),
        ),
    ]
