# Generated by Django 3.1.14 on 2022-05-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generatereport', '0083_auto_20220522_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsheet',
            name='cover_report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
