# Generated by Django 2.2.3 on 2021-05-10 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbmanagement', '0017_auto_20210116_1214'),
        ('sheetcreator', '0072_auto_20210510_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='VelocitySheetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('air_moving_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.SheetEquipment')),
                ('sheet_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheetField')),
            ],
        ),
    ]
