# Generated by Django 5.1.6 on 2025-03-30 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbmanagement', '0001_initial'),
        ('sheetcreator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VelocityEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity_data', models.BooleanField(default=False)),
                ('velocity_row', models.SmallIntegerField(default=0)),
                ('velocity_col', models.SmallIntegerField(default=0)),
                ('air_moving_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.sheetequipment')),
            ],
        ),
        migrations.CreateModel(
            name='VelocitySheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('sheet_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheetfield')),
                ('velocity_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsheetvelocity.velocityequipment')),
            ],
        ),
        migrations.CreateModel(
            name='VelocitySheetTableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.SmallIntegerField()),
                ('col', models.SmallIntegerField()),
                ('value', models.CharField(max_length=500)),
                ('velocity_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsheetvelocity.velocityequipment')),
            ],
        ),
    ]
