# Generated by Django 2.2.3 on 2021-05-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0074_auto_20210511_1519'),
        ('testsheetvelocity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VelocitySheetTableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.SmallIntegerField()),
                ('col', models.SmallIntegerField()),
                ('value', models.CharField(max_length=50)),
                ('air_moving_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.SheetEquipment')),
            ],
        ),
    ]
