# Generated by Django 2.2.3 on 2021-05-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0077_auto_20210518_2032'),
        ('testsheetvelocity', '0002_velocitysheettabledata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='velocitysheetdata',
            name='air_moving_equipment',
        ),
        migrations.AlterField(
            model_name='velocitysheetdata',
            name='value',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='velocitysheettabledata',
            name='value',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='VelocityEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity_data', models.BooleanField(default=False)),
                ('velocity_row', models.SmallIntegerField(default=0)),
                ('velocity_col', models.SmallIntegerField(default=0)),
                ('air_moving_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.SheetEquipment')),
            ],
        ),
        migrations.AddField(
            model_name='velocitysheetdata',
            name='velocity_equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testsheetvelocity.VelocityEquipment'),
            preserve_default=False,
        ),
    ]
