# Generated by Django 2.2.3 on 2021-05-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetvelocity', '0003_auto_20210518_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='velocitysheettabledata',
            name='air_moving_equipment',
        ),
        migrations.AddField(
            model_name='velocitysheettabledata',
            name='velocity_equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testsheetvelocity.VelocityEquipment'),
            preserve_default=False,
        ),
    ]
