from django.urls import path

from .views import (
    ScheduleListView,
    ScheduleUpdateView,
    ScheduleArchiveView,
    ScheduleDeleteView,
    ScheduleCreateView,
    UserTecListView,
    ScheduleTecListView,
    ScheduleTecDetailView,
    ScheduleTecCreateView,
    ScheduleTecUpdateView,
    ScheduleTecDeleteView,
)

urlpatterns = [
    path(
        'schedule/get/',
        ScheduleListView.as_view(),
        name='schedule-list'
    ),
    path(
        'schedule/create/',
        ScheduleCreateView.as_view(),
        name='schedule-create'
    ),
    path(
        'schedule/update/<int:schedule_id>/',
        ScheduleUpdateView.as_view(),
        name='schedule-update'
    ),
    path(
        'schedule/archive/<int:id>/',
        ScheduleArchiveView.as_view(),
        name='schedule-archive'
    ),
    path(
        'schedule/delete/<int:schedule_id>/',
        ScheduleDeleteView.as_view(),
        name='schedule-delete'
    ),
    path(
        'schedule/user-tec/<int:schedule_id>/',
        UserTecListView.as_view(),
        name='user-tec-list'
    ),
    path(
        'schedule/techs/',
        ScheduleTecListView.as_view(),
        name='schedule-tech-list'
    ),
    path(
        'schedule/tech/<int:schedule_id>/',
        ScheduleTecDetailView.as_view(),
        name='schedule-tec-detail'
    ),
    path(
        'schedule/tech/create/<int:schedule_id>/',
        ScheduleTecCreateView.as_view(),
        name='schedule-create'
    ),
    path(
        'schedule/tech/update/<int:tech_id>/',
        ScheduleTecUpdateView.as_view(),
        name='schedule-update'
    ),
    path(
        'schedule/tech/delete/<int:tech_id>/',
        ScheduleTecDeleteView.as_view(),
        name='schedule-tech-delete'
    ),

]
