# Generated by Django 3.0.2 on 2020-05-28 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='iBidFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(default='05/28/2020', null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/ibidfiles')),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('archive', models.BooleanField(default=False)),
                ('hidden_for_customer', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Maximum Upload Size: 250.0MB', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Person')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Project')),
            ],
            options={
                'verbose_name': 'Bid Files Management',
                'verbose_name_plural': 'Bid Files Management',
                'ordering': ['-due_date'],
            },
        ),
    ]
