# Generated by Django 2.2.3 on 2020-03-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ibfm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='03/17/2020', null=True),
        ),
        migrations.AlterField(
            model_name='ibidfile',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/ibidfiles'),
        ),
    ]
