# Generated by Django 2.2.3 on 2020-03-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0002_auto_20200317_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='03/20/2020', null=True),
        ),
    ]
