# Generated by Django 4.2.11 on 2024-06-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0002_alter_ibidfile_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='06/15/2024', null=True),
        ),
    ]
