# Generated by Django 2.2.3 on 2020-06-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0002_auto_20200530_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='06/11/2020', null=True),
        ),
    ]
