# Generated by Django 2.2.3 on 2020-03-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ibfm', '0003_auto_20200320_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='03/22/2020', null=True),
        ),
    ]
