# Generated by Django 3.0.2 on 2020-06-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0003_auto_20200611_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='06/23/2020', null=True),
        ),
    ]
