# Generated by Django 3.0.2 on 2020-07-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0006_auto_20200711_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='07/12/2020', null=True),
        ),
    ]
