# Generated by Django 3.0.2 on 2020-09-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0008_auto_20200914_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='09/15/2020', null=True),
        ),
    ]
