# Generated by Django 3.0.2 on 2020-09-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0011_auto_20200924_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='09/26/2020', null=True),
        ),
    ]
