# Generated by Django 3.1.3 on 2020-11-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0011_auto_20201115_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='11/16/2020', null=True),
        ),
    ]
