# Generated by Django 3.0.2 on 2020-05-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0012_auto_20200502_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='05/03/2020', null=True),
        ),
    ]
