# Generated by Django 3.1.3 on 2020-11-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0012_auto_20201116_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='11/17/2020', null=True),
        ),
    ]
