# Generated by Django 3.1.3 on 2020-12-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0014_auto_20201203_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='12/05/2020', null=True),
        ),
    ]
