# Generated by Django 2.2.3 on 2020-10-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0015_auto_20200929_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='10/01/2020', null=True),
        ),
    ]
