# Generated by Django 4.2.11 on 2024-10-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0015_alter_ibidfile_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='10/18/2024', null=True),
        ),
    ]
