# Generated by Django 3.1.3 on 2020-12-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0016_auto_20201206_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='12/07/2020', null=True),
        ),
    ]
