# Generated by Django 2.2.3 on 2020-10-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0019_auto_20201014_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='10/18/2020', null=True),
        ),
    ]
