# Generated by Django 2.2.3 on 2021-01-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0021_auto_20210104_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='01/11/2021', null=True),
        ),
    ]
