# Generated by Django 2.2.3 on 2021-01-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0022_auto_20210111_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='01/16/2021', null=True),
        ),
    ]
