# Generated by Django 2.2.3 on 2021-03-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0031_auto_20210226_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='03/04/2021', null=True),
        ),
    ]
