# Generated by Django 2.2.3 on 2021-03-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0032_auto_20210304_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='03/06/2021', null=True),
        ),
    ]
