# Generated by Django 2.2.3 on 2021-04-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0047_auto_20210417_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='04/19/2021', null=True),
        ),
    ]
