# Generated by Django 2.2.3 on 2021-05-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0053_auto_20210428_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='05/04/2021', null=True),
        ),
    ]
