# Generated by Django 2.2.3 on 2021-05-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0055_auto_20210505_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='05/06/2021', null=True),
        ),
    ]
