# Generated by Django 2.2.3 on 2021-06-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0066_auto_20210607_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='06/08/2021', null=True),
        ),
    ]
