# Generated by Django 2.2.3 on 2021-08-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0068_auto_20210729_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='08/03/2021', null=True),
        ),
    ]
