# Generated by Django 2.2.3 on 2021-06-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0069_auto_20210623_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='06/24/2021', null=True),
        ),
    ]
