# Generated by Django 2.2.3 on 2021-08-09 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0070_auto_20210806_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='customer',
            field=models.ForeignKey(help_text='Maximum Upload Size: 500.0MB', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Person'),
        ),
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='08/09/2021', null=True),
        ),
    ]
