# Generated by Django 2.2.3 on 2021-07-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0070_auto_20210624_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='07/06/2021', null=True),
        ),
    ]
