# Generated by Django 2.2.3 on 2021-07-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0072_auto_20210712_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='07/13/2021', null=True),
        ),
    ]
