# Generated by Django 2.2.3 on 2022-04-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0079_auto_20220319_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='04/29/2022', null=True),
        ),
    ]
