# Generated by Django 3.2.13 on 2022-04-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0080_auto_20220429_1045'),
        ('ibfm', '0084_alter_ibidfile_due_date'),
    ]

    operations = [
    ]
