# Generated by Django 3.1.14 on 2022-05-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0086_alter_ibidfile_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='05/22/2022', null=True),
        ),
    ]
