# Generated by Django 4.2.6 on 2024-04-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibfm', '0091_alter_ibidfile_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ibidfile',
            name='due_date',
            field=models.DateField(default='04/29/2024', null=True),
        ),
    ]
