# Generated by Django 2.2.3 on 2021-07-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetairmovingequipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airmovingequipmentsheetdata',
            old_name='primary_heat_exchanger_equipment',
            new_name='air_moving_equipment_equipment',
        ),
    ]
