# Generated by Django 4.2.11 on 2024-05-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbmanagement', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirTerminalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_no', models.SmallIntegerField()),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Supply'), (2, 'Return'), (3, 'Outside'), (4, 'Other')], default=1)),
                ('equipment_name', models.CharField(max_length=255, null=True)),
                ('other_group', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_date', models.DateField(null=True)),
                ('system', models.CharField(max_length=50)),
                ('number_of_equipment_groups', models.IntegerField(default=1)),
                ('archive', models.BooleanField(default=False)),
                ('rogue_design_data_entry_completed', models.BooleanField(default=False)),
                ('rogue_actual_data_entry_completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('test_sheet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheet')),
            ],
            options={
                'verbose_name': 'VAV & Air Terminal Sheets',
                'verbose_name_plural': 'VAV & Air Terminal Sheets',
            },
        ),
        migrations.CreateModel(
            name='DataSheetEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_group', models.CharField(default='A', max_length=50)),
                ('number_of_supply_air_terminal', models.SmallIntegerField(default=0)),
                ('main_data_entry_completed', models.BooleanField(default=False)),
                ('design_data_entry_completed', models.BooleanField(default=False)),
                ('actual_data_entry_completed', models.BooleanField(default=False)),
                ('terminal_design_data_entry_completed', models.BooleanField(default=False)),
                ('terminal_actual_data_entry_completed', models.BooleanField(default=False)),
                ('field_order', models.PositiveIntegerField(default=0)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipmentdb')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipment')),
            ],
            options={
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_date', models.DateField(null=True)),
                ('system', models.CharField(max_length=50)),
                ('archive', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('test_sheet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheet')),
            ],
            options={
                'verbose_name': 'Air Moving Sheets',
                'verbose_name_plural': 'Air Moving Sheets',
            },
        ),
        migrations.CreateModel(
            name='SheetActualDataCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_title', models.CharField(max_length=50)),
                ('test_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheet')),
            ],
        ),
        migrations.CreateModel(
            name='SheetEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_supply_air_terminal', models.SmallIntegerField(default=0)),
                ('number_of_return_air_terminal', models.SmallIntegerField(default=0)),
                ('number_of_outside_air_terminal', models.SmallIntegerField(default=0)),
                ('number_of_exhaust_air_terminal', models.SmallIntegerField(default=0)),
                ('main_data_entry_completed', models.BooleanField(default=False)),
                ('design_data_entry_completed', models.BooleanField(default=False)),
                ('actual_data_entry_completed', models.BooleanField(default=False)),
                ('terminal_design_data_entry_completed', models.BooleanField(default=False)),
                ('terminal_actual_data_entry_completed', models.BooleanField(default=False)),
                ('velocity_data', models.BooleanField(default=False)),
                ('field_order', models.PositiveIntegerField(default=0)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipmentdb')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipment')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.sheet')),
            ],
            options={
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='TestSheetGeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheetcolumn')),
                ('sheet_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.datasheetequipment')),
            ],
        ),
        migrations.CreateModel(
            name='TestSheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.PositiveSmallIntegerField(choices=[(1, 'Design'), (2, 'Actual')], default=1)),
                ('value', models.CharField(max_length=500)),
                ('sheet_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.datasheetequipment')),
                ('sheet_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheetfield')),
            ],
        ),
        migrations.CreateModel(
            name='SheetEquipmentCustomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.sheetactualdatacustomfield')),
                ('sheet_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.sheetequipment')),
            ],
        ),
        migrations.CreateModel(
            name='SheetEquipmentCommonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheetcolumn')),
                ('sheet_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.sheetequipment')),
            ],
        ),
        migrations.CreateModel(
            name='SheetEquipmentActualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.equipmentcustomfield')),
                ('sheet_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.sheetequipment')),
            ],
        ),
        migrations.AddField(
            model_name='datasheetequipment',
            name='inherited_from_air_moving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sheetcreator.sheetequipment'),
        ),
        migrations.AddField(
            model_name='datasheetequipment',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.datasheet'),
        ),
        migrations.CreateModel(
            name='AirTerminalSheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.PositiveSmallIntegerField(choices=[(1, 'Design'), (2, 'Actual')], default=1)),
                ('value', models.CharField(max_length=500)),
                ('air_terminal_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.airterminalequipment')),
                ('sheet_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheetfield')),
            ],
        ),
        migrations.AddField(
            model_name='airterminalequipment',
            name='air_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.sheetequipment'),
        ),
        migrations.AddField(
            model_name='airterminalequipment',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.airterminalcode'),
        ),
        migrations.AddField(
            model_name='airterminalequipment',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.datasheet'),
        ),
        migrations.AddField(
            model_name='airterminalequipment',
            name='vav_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.datasheetequipment'),
        ),
    ]
