# Generated by Django 2.2.3 on 2020-10-24 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbmanagement', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_date', models.DateField(default='10/24/2020', null=True)),
                ('system', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('test_sheet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheet')),
            ],
        ),
        migrations.CreateModel(
            name='SheetActualDataCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_title', models.CharField(max_length=50)),
                ('test_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheet')),
            ],
        ),
        migrations.CreateModel(
            name='SheetEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_data_entry_completed', models.BooleanField(default=False)),
                ('design_data_entry_completed', models.BooleanField(default=False)),
                ('actual_data_entry_completed', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.EquipmentDb')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.Equipment')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.Sheet')),
            ],
        ),
        migrations.CreateModel(
            name='TestSheetColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_title', models.CharField(max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('test_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheet')),
            ],
        ),
        migrations.CreateModel(
            name='SheetEquipmentCustomData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.SheetActualDataCustomField')),
                ('sheet_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.SheetEquipment')),
            ],
        ),
        migrations.CreateModel(
            name='SheetEquipmentCommonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.TestSheetColumn')),
                ('sheet_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.SheetEquipment')),
            ],
        ),
        migrations.CreateModel(
            name='SheetEquipmentActualData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.EquipmentCustomField')),
                ('sheet_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.SheetEquipment')),
            ],
        ),
    ]
