# Generated by Django 3.0.2 on 2020-06-05 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200605_1818'),
        ('sheetcreator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
