# Generated by Django 4.2.11 on 2024-05-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetequipment',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
