# Generated by Django 2.2.3 on 2020-10-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('dbmanagement', '0005_auto_20201024_1503'),
        ('sheetcreator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_date', models.DateField(default='10/24/2020', null=True)),
                ('system', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('test_sheet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheet')),
            ],
        ),
        migrations.CreateModel(
            name='DataSheetEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_data_entry_completed', models.BooleanField(default=False)),
                ('design_data_entry_completed', models.BooleanField(default=False)),
                ('actual_data_entry_completed', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.EquipmentDb')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.Equipment')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.DataSheet')),
            ],
        ),
        migrations.CreateModel(
            name='TestSheetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.PositiveSmallIntegerField(choices=[(1, 'Design'), (2, 'Actual')], default=1)),
                ('value', models.CharField(max_length=50)),
                ('sheet_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.DataSheetEquipment')),
            ],
        ),
    ]
