# Generated by Django 4.2.11 on 2024-05-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0002_datasheetequipment_is_confirmed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasheetequipment',
            old_name='is_confirmed',
            new_name='actual_data_entry_confirmed',
        ),
        migrations.RenameField(
            model_name='sheetequipment',
            old_name='is_confirmed',
            new_name='actual_data_entry_confirmed',
        ),
        migrations.AddField(
            model_name='datasheetequipment',
            name='design_data_entry_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasheetequipment',
            name='main_data_entry_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='design_data_entry_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='main_data_entry_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
