# Generated by Django 3.0.2 on 2020-06-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0002_auto_20200605_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetequipment',
            name='actual_data_entry_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='main_data_entry_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='06/06/2020', null=True),
        ),
    ]
