# Generated by Django 2.2.3 on 2020-10-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0002_datasheet_datasheetequipment_testsheetdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSheetGeneralData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.TestSheetColumn')),
                ('sheet_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.DataSheetEquipment')),
            ],
        ),
    ]
