# Generated by Django 3.0.2 on 2020-06-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0003_auto_20200606_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetequipment',
            name='quantity',
        ),
    ]
