# Generated by Django 4.2.11 on 2024-06-15 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0003_rename_is_confirmed_datasheetequipment_actual_data_entry_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheetequipment',
            name='actual_data_entry_confirmed',
        ),
        migrations.RemoveField(
            model_name='datasheetequipment',
            name='design_data_entry_confirmed',
        ),
        migrations.RemoveField(
            model_name='datasheetequipment',
            name='main_data_entry_confirmed',
        ),
        migrations.RemoveField(
            model_name='sheetequipment',
            name='actual_data_entry_confirmed',
        ),
        migrations.RemoveField(
            model_name='sheetequipment',
            name='design_data_entry_confirmed',
        ),
        migrations.RemoveField(
            model_name='sheetequipment',
            name='main_data_entry_confirmed',
        ),
    ]
