# Generated by Django 2.2.3 on 2020-10-24 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0006_auto_20201024_1843'),
        ('sheetcreator', '0003_testsheetgeneraldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheetdata',
            name='sheet_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheetField'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='sheet_date',
            field=models.DateField(default='10/25/2020', null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='10/25/2020', null=True),
        ),
    ]
