# Generated by Django 4.2.11 on 2024-06-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0002_equipmentdb_actual_data_entry_confirmed_and_more'),
        ('sheetcreator', '0004_remove_datasheetequipment_actual_data_entry_confirmed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SheetEquipmentCommonData',
            new_name='SECD',
        ),
    ]
