# Generated by Django 3.0.2 on 2020-06-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0003_auto_20200608_2113'),
        ('sheetcreator', '0004_remove_sheetequipment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='06/08/2020', null=True),
        ),
        migrations.AlterField(
            model_name='sheetequipmentactualdata',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.EquipmentCustomField'),
        ),
    ]
