# Generated by Django 2.2.3 on 2020-10-24 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0004_auto_20201025_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetequipmentcommondata',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheetColumn'),
        ),
        migrations.AlterField(
            model_name='testsheetgeneraldata',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheetColumn'),
        ),
        migrations.DeleteModel(
            name='TestSheetColumn',
        ),
    ]
