# Generated by Django 3.0.2 on 2020-06-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0005_auto_20200608_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SheetEquipmentMainData',
            new_name='SheetEquipmentCommonData',
        ),
    ]
