# Generated by Django 3.0.2 on 2020-06-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0003_auto_20200608_2113'),
        ('sheetcreator', '0007_auto_20200608_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.Equipment'),
        ),
    ]
