# Generated by Django 3.0.2 on 2020-06-08 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0003_auto_20200608_2113'),
        ('sheetcreator', '0008_auto_20200608_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetequipment',
            name='equipment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.Equipment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sheetequipment',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.EquipmentDb'),
        ),
    ]
