# Generated by Django 3.0.2 on 2020-06-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0009_auto_20200608_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='06/09/2020', null=True),
        ),
    ]
