# Generated by Django 3.0.7 on 2020-06-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0010_auto_20200609_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='06/17/2020', null=True),
        ),
    ]
