# Generated by Django 2.2.3 on 2020-11-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0010_auto_20201107_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetequipment',
            name='number_of_return_air_terminal',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='number_of_supply_air_terminal',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='sheet_date',
            field=models.DateField(default='11/11/2020', null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='11/11/2020', null=True),
        ),
    ]
