# Generated by Django 3.0.2 on 2020-06-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200528_1807'),
        ('sheetcreator', '0011_auto_20200617_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='06/23/2020', null=True),
        ),
        migrations.CreateModel(
            name='SheetEquipmentCustomData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('sheet_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.SheetEquipment')),
            ],
        ),
        migrations.CreateModel(
            name='SheetActualDataCustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_title', models.CharField(max_length=50)),
                ('test_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TestSheet')),
            ],
        ),
    ]
