# Generated by Django 2.2.3 on 2020-11-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0011_auto_20201111_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetequipment',
            name='number_of_return_air_terminal',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasheetequipment',
            name='number_of_supply_air_terminal',
            field=models.SmallIntegerField(default=0),
        ),
    ]
