# Generated by Django 2.2.3 on 2020-11-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0012_auto_20201111_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheetequipment',
            name='number_of_return_air_terminal',
        ),
    ]
