# Generated by Django 3.0.2 on 2020-06-24 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0012_auto_20200623_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='06/24/2020', null=True),
        ),
        migrations.AlterField(
            model_name='sheetequipmentcustomdata',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.SheetActualDataCustomField'),
        ),
    ]
