# Generated by Django 2.2.3 on 2020-07-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0013_auto_20200624_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsheetcolumn',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='07/06/2020', null=True),
        ),
    ]
