# Generated by Django 3.0.2 on 2020-07-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0014_auto_20200706_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='07/11/2020', null=True),
        ),
    ]
