# Generated by Django 2.2.3 on 2020-08-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0014_auto_20200706_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetequipment',
            name='design_data_entry_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='08/28/2020', null=True),
        ),
    ]
