# Generated by Django 3.1.3 on 2020-11-14 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0011_auto_20201107_2116'),
        ('sheetcreator', '0015_auto_20201113_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirTerminalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=5)),
                ('default', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AirTerminalEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_no', models.SmallIntegerField()),
                ('air_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.sheetequipment')),
                ('code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.airterminalcode')),
            ],
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='sheet_date',
            field=models.DateField(default='11/14/2020', null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='11/14/2020', null=True),
        ),
        migrations.CreateModel(
            name='AirTerminalSheetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.PositiveSmallIntegerField(choices=[(1, 'Design'), (2, 'Actual')], default=1)),
                ('value', models.CharField(max_length=50)),
                ('air_terminal_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.airterminalequipment')),
                ('sheet_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.testsheetfield')),
            ],
        ),
        migrations.AddField(
            model_name='airterminalequipment',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.sheet'),
        ),
        migrations.AddField(
            model_name='airterminalequipment',
            name='vav_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.datasheetequipment'),
        ),
    ]
