# Generated by Django 3.0.2 on 2020-07-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0015_auto_20200711_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetequipment',
            name='design_data_entry_completed',
            field=models.BooleanField(default=False),
        ),
    ]
