# Generated by Django 3.0.2 on 2020-07-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0016_sheetequipment_design_data_entry_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='07/12/2020', null=True),
        ),
    ]
