# Generated by Django 3.1.3 on 2020-11-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0016_auto_20201114_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airterminalcode',
            old_name='Name',
            new_name='name',
        ),
    ]
