# Generated by Django 3.1.3 on 2020-11-14 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0012_airterminalcode'),
        ('sheetcreator', '0017_auto_20201114_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airterminalequipment',
            name='code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.airterminalcode'),
        ),
        migrations.DeleteModel(
            name='AirTerminalCode',
        ),
    ]
