# Generated by Django 3.0.2 on 2020-09-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0017_auto_20200712_1851'),
        ('sheetcreator', '0015_auto_20200828_1539'),
    ]

    operations = [
    ]
