# Generated by Django 3.0.2 on 2020-09-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0018_merge_20200909_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='09/14/2020', null=True),
        ),
    ]
