# Generated by Django 3.1.3 on 2020-11-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0018_auto_20201114_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airterminalequipment',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.datasheet'),
        ),
    ]
