# Generated by Django 3.1.3 on 2020-11-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0019_auto_20201114_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetequipment',
            name='terminal_actual_data_entry_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='terminal_design_data_entry_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='sheet_date',
            field=models.DateField(default='11/15/2020', null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='11/15/2020', null=True),
        ),
    ]
