# Generated by Django 3.1.3 on 2020-11-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0020_auto_20201115_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='airterminalequipment',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Supply'), (2, 'Return')], default=1),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='sheet_date',
            field=models.DateField(default='11/16/2020', null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='11/16/2020', null=True),
        ),
    ]
