# Generated by Django 3.1.3 on 2020-11-17 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanagement', '0013_auto_20201114_1207'),
        ('sheetcreator', '0021_auto_20201116_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airterminalequipment',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.airterminalcode'),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='sheet_date',
            field=models.DateField(default='11/17/2020', null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='11/17/2020', null=True),
        ),
    ]
