# Generated by Django 2.2.3 on 2020-12-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0028_auto_20201214_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sheet',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='sheet_date',
            field=models.DateField(default='12/28/2020', null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='12/28/2020', null=True),
        ),
    ]
