# Generated by Django 2.2.3 on 2021-01-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0030_auto_20210104_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetequipment',
            name='number_of_outside_air_terminal',
            field=models.SmallIntegerField(default=0),
        ),
    ]
