# Generated by Django 2.2.3 on 2021-01-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0033_auto_20210116_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasheetequipment',
            options={'ordering': ['field_order']},
        ),
        migrations.AddField(
            model_name='datasheetequipment',
            name='field_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='sheet_date',
            field=models.DateField(default='01/25/2021', null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='01/25/2021', null=True),
        ),
    ]
