# Generated by Django 2.2.3 on 2021-01-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0034_auto_20210125_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheetequipment',
            options={'ordering': ['field_order']},
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='field_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
