# Generated by Django 2.2.3 on 2021-01-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0035_auto_20210125_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasheet',
            options={'verbose_name': 'VAV & Air Terminal Sheets', 'verbose_name_plural': 'VAV & Air Terminal Sheets'},
        ),
        migrations.AlterModelOptions(
            name='sheet',
            options={'verbose_name': 'Air Moving Sheets', 'verbose_name_plural': 'Air Moving Sheets'},
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='number_of_exhaust_fan',
            field=models.SmallIntegerField(default=0),
        ),
    ]
