# Generated by Django 2.2.3 on 2021-01-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0036_auto_20210125_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetequipment',
            name='number_of_exhaust_fan',
        ),
    ]
