# Generated by Django 2.2.3 on 2021-01-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0037_remove_sheetequipment_number_of_exhaust_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetequipment',
            name='number_of_any_other',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='sheet_date',
            field=models.DateField(default='01/28/2021', null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='01/28/2021', null=True),
        ),
    ]
