# Generated by Django 2.2.3 on 2021-01-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0039_auto_20210129_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airterminalequipment',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Supply'), (2, 'Return'), (3, 'Outside'), (4, 'Other')], default=1),
        ),
    ]
