# Generated by Django 2.2.3 on 2021-01-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0040_auto_20210129_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='airterminalequipment',
            name='equipment_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
