# Generated by Django 2.2.3 on 2021-04-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0059_auto_20210414_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='sheet_date',
            field=models.DateField(default='04/15/2021', null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='04/15/2021', null=True),
        ),
    ]
