# Generated by Django 2.2.3 on 2021-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0067_auto_20210424_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='sheet_date',
            field=models.DateField(default='04/28/2021', null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='04/28/2021', null=True),
        ),
    ]
