# Generated by Django 2.2.3 on 2021-05-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0072_auto_20210510_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetequipment',
            name='velocity_data',
            field=models.BooleanField(default=False),
        ),
    ]
