# Generated by Django 2.2.3 on 2021-05-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0074_auto_20210511_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetequipment',
            name='velocity_col',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='velocity_row',
            field=models.SmallIntegerField(default=0),
        ),
    ]
