# Generated by Django 2.2.3 on 2021-05-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0075_auto_20210511_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='sheet_date',
            field=models.DateField(default='05/18/2021', null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='05/18/2021', null=True),
        ),
    ]
