# Generated by Django 2.2.3 on 2021-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0076_auto_20210518_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetequipment',
            name='velocity_col',
        ),
        migrations.RemoveField(
            model_name='sheetequipment',
            name='velocity_data',
        ),
        migrations.RemoveField(
            model_name='sheetequipment',
            name='velocity_row',
        ),
        migrations.AlterField(
            model_name='airterminalsheetdata',
            name='value',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sheetequipmentactualdata',
            name='value',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sheetequipmentcommondata',
            name='value',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sheetequipmentcustomdata',
            name='value',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testsheetdata',
            name='value',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testsheetgeneraldata',
            name='value',
            field=models.CharField(max_length=500),
        ),
    ]
