# Generated by Django 2.2.3 on 2021-05-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0077_auto_20210518_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetequipment',
            name='velocity_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='sheet_date',
            field=models.DateField(default='05/19/2021', null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='05/19/2021', null=True),
        ),
    ]
