# Generated by Django 2.2.3 on 2021-07-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0092_auto_20210718_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='sheet_date',
            field=models.DateField(default='07/23/2021', null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_date',
            field=models.DateField(default='07/23/2021', null=True),
        ),
    ]
