# Generated by Django 4.0.4 on 2022-04-17 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0106_auto_20220319_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetequipment',
            name='inherited_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sheetcreator.datasheetequipment'),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='inherited_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sheetcreator.sheetequipment'),
        ),
    ]
