# Generated by Django 4.0.4 on 2022-04-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0107_datasheetequipment_inherited_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetequipment',
            name='inherited_from',
        ),
        migrations.AddField(
            model_name='datasheetequipment',
            name='inherited_from_air_moving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sheetcreator.sheetequipment'),
        ),
    ]
