# Generated by Django 4.0.4 on 2022-04-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0108_remove_sheetequipment_inherited_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheetequipment',
            name='inherited_from',
        ),
    ]
