# Generated by Django 4.0.4 on 2022-04-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0109_remove_datasheetequipment_inherited_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='airterminalequipment',
            name='other_group',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
