# Generated by Django 4.0.4 on 2022-04-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0110_airterminalequipment_other_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheet',
            name='rogue_actual_data_entry_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='rogue_design_data_entry_completed',
            field=models.BooleanField(default=False),
        ),
    ]
