# Generated by Django 3.2.13 on 2022-04-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0111_datasheet_rogue_actual_data_entry_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasheetequipment',
            name='supply_total_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='design_outside_total_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='design_return_total_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='design_supply_total_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='final_outside_total_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='final_return_total_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='final_supply_total_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='initial_outside_total_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='initial_return_total_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheetequipment',
            name='initial_supply_total_override',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
