# Generated by Django 3.2.13 on 2022-04-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0112_auto_20220429_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasheetequipment',
            name='supply_total_override',
        ),
        migrations.RemoveField(
            model_name='sheetequipment',
            name='design_outside_total_override',
        ),
        migrations.RemoveField(
            model_name='sheetequipment',
            name='design_return_total_override',
        ),
        migrations.RemoveField(
            model_name='sheetequipment',
            name='design_supply_total_override',
        ),
        migrations.RemoveField(
            model_name='sheetequipment',
            name='final_outside_total_override',
        ),
        migrations.RemoveField(
            model_name='sheetequipment',
            name='final_return_total_override',
        ),
        migrations.RemoveField(
            model_name='sheetequipment',
            name='final_supply_total_override',
        ),
        migrations.RemoveField(
            model_name='sheetequipment',
            name='initial_outside_total_override',
        ),
        migrations.RemoveField(
            model_name='sheetequipment',
            name='initial_return_total_override',
        ),
        migrations.RemoveField(
            model_name='sheetequipment',
            name='initial_supply_total_override',
        ),
    ]
