# Generated by Django 3.1.14 on 2022-05-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetcreator', '0113_auto_20220429_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheetequipment',
            old_name='number_of_any_other',
            new_name='number_of_exhaust_air_terminal',
        ),
    ]
