# Generated by Django 2.2.3 on 2020-03-27 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0011_auto_20200301_1915'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0012_auto_20200327_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_contractor',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='core.Person')),
                ('assigned_to_employee',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='assigned_to_employee', to=settings.AUTH_USER_MODEL)),
                ('created_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'verbose_name': 'Schedule List',
                'verbose_name_plural': 'Schedule List',
                'ordering': ['-created_on'],
            },
        ),
    ]
