# Generated by Django 2.2.3 on 2020-10-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
