# Generated by Django 2.2.3 on 2020-03-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
