# Generated by Django 2.2.3 on 2020-03-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schedule', '0002_schedule_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='scheduled_for',
            field=models.DateTimeField(default='03/27/2020 18:07:42'),
        ),
    ]
