# Generated by Django 2.2.3 on 2020-10-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedule_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='scheduled_for',
            new_name='schedule_start',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='duration',
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
