# Generated by Django 2.2.3 on 2020-10-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20201014_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_end',
            field=models.DateTimeField(),
        ),
    ]
