# Generated by Django 2.2.3 on 2020-03-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20200327_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='scheduled_for',
            field=models.DateTimeField(default='03/27/2020 20:45'),
        ),
    ]
