# Generated by Django 2.2.3 on 2020-03-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20200327_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='scheduled_for',
            field=models.DateTimeField(),
        ),
    ]
