# Generated by Django 4.2.11 on 2024-05-11 07:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_number', models.CharField(max_length=30)),
                ('date', models.DateField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(blank=True, max_length=30, null=True)),
                ('os', models.CharField(blank=True, max_length=20, null=True)),
                ('release_date', models.DateField(blank=True, default='05/11/2024', null=True)),
                ('control_file_url', models.URLField(blank=True, max_length=255, null=True)),
                ('documentation', models.FileField(blank=True, null=True, upload_to='uploads/control_system_documentations')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['manufacturer'],
            },
        ),
        migrations.CreateModel(
            name='ControlSystemManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=30)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('tel', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('mail', models.EmailField(blank=True, max_length=55)),
                ('web', models.CharField(blank=True, max_length=55)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['manufacturer_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=10)),
                ('po_number', models.CharField(max_length=30)),
                ('date_po_received', models.DateField(blank=True, null=True)),
                ('estimated_date_of_project', models.DateField(blank=True, null=True)),
                ('final_offset', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('predemo_offset', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('equipment_submittal', models.FileField(blank=True, null=True, upload_to='uploads/order_equipment_submittal')),
                ('colored_drawing', models.FileField(blank=True, null=True, upload_to='uploads/order_colored_drawing')),
                ('report_colored_drawing', models.FileField(blank=True, null=True, upload_to='uploads/order_colored_drawing/report')),
                ('colored_drawing_finalize', models.BooleanField(default=False)),
                ('field_draw', models.FileField(blank=True, null=True, upload_to='uploads/field_draw')),
                ('general_notes_and_comments', django_quill.fields.QuillField(blank=True, null=True)),
                ('general_notes_and_comments_finalize', models.BooleanField(default=False)),
                ('site_pictures', models.FileField(blank=True, null=True, upload_to='uploads/order_site_pictures')),
                ('test_sheets', models.FileField(blank=True, null=True, upload_to='uploads/order_test_sheets')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('fully_settled', models.BooleanField(default=False)),
                ('order_settled_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('completion_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('pre_demo_completion_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
                ('partial_job_done', models.BooleanField(default=False)),
                ('architect_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person')),
                ('control_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.controlsystem')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimator.proposal')),
            ],
            options={
                'verbose_name': 'Order List',
                'verbose_name_plural': 'Order List',
                'ordering': ['-proposal'],
            },
        ),
        migrations.CreateModel(
            name='TechLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed_drawing', models.BooleanField(default=False)),
                ('schedule_drawing', models.BooleanField(default=False)),
                ('mechanical_drawing', models.BooleanField(default=False)),
                ('tech_test_sheets', models.BooleanField(default=False)),
                ('point_of_contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('point_of_contact_cell_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('point_of_contact_office_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('tech_notes', models.TextField(blank=True, max_length=255, null=True)),
                ('label_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.techlabelmodel')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='TechLabelExtraFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('tech_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.techlabel')),
            ],
        ),
        migrations.AddField(
            model_name='controlsystem',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.controlsystemmanufacturer'),
        ),
        migrations.CreateModel(
            name='ChangeOrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('change_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.changeorder')),
            ],
        ),
        migrations.AddField(
            model_name='changeorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
        migrations.AlterUniqueTogether(
            name='changeorder',
            unique_together={('co_number', 'order')},
        ),
    ]
