# Generated by Django 2.2.3 on 2020-01-19 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=10)),
                ('architect_name', models.CharField(blank=True, max_length=100, null=True)),
                ('po_number', models.CharField(max_length=30)),
                ('date_po_received', models.DateField(default='01/19/2020')),
                ('estimated_date_of_project', models.DateField(default='01/19/2020')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('archive', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
                (
                    'proposal',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimator.Proposal')),
            ],
            options={
                'verbose_name': 'Order List',
                'verbose_name_plural': 'Order List',
                'ordering': ['-proposal'],
            },
        ),
    ]
