# Generated by Django 2.2.3 on 2019-09-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.TextField(max_length=20),
        ),
    ]
