# Generated by Django 2.2.3 on 2019-12-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_po_received',
            field=models.DateField(default='12/24/2019'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_date_of_project',
            field=models.DateField(default='12/24/2019'),
        ),
    ]
