# Generated by Django 3.0.2 on 2020-05-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='05/30/2020', null=True),
        ),
    ]
