# Generated by Django 2.2.3 on 2020-10-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201025_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlsystem',
            name='manufacturer_contact_info',
        ),
        migrations.AddField(
            model_name='controlsystemmanufacturer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='controlsystemmanufacturer',
            name='fax',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='controlsystemmanufacturer',
            name='mail',
            field=models.EmailField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='controlsystemmanufacturer',
            name='tel',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='controlsystemmanufacturer',
            name='web',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='10/26/2020', null=True),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='10/26/2020', null=True),
        ),
    ]
