# Generated by Django 2.2.3 on 2020-01-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200120_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_po_received',
            field=models.DateField(default='01/29/2020'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_date_of_project',
            field=models.DateField(default='01/29/2020'),
        ),
    ]
