# Generated by Django 2.2.3 on 2019-09-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190923_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='po_number',
            field=models.CharField(max_length=30),
        ),
    ]
