# Generated by Django 2.2.3 on 2020-02-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200129_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_po_received',
            field=models.DateField(default='02/09/2020'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_date_of_project',
            field=models.DateField(default='02/09/2020'),
        ),
    ]
