# Generated by Django 2.2.3 on 2019-10-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191006_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_po_received',
            field=models.DateField(default='10/13/2019'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_date_of_project',
            field=models.DateField(default='10/13/2019'),
        ),
    ]
