# Generated by Django 3.0.2 on 2020-09-15 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testsheet_sheet_generator'),
        ('order', '0008_auto_20200914_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSystemManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='09/15/2020', null=True),
        ),
        migrations.CreateModel(
            name='ControlSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(blank=True, max_length=30, null=True)),
                ('os', models.CharField(blank=True, max_length=20, null=True)),
                ('release_date', models.DateField(default='09/15/2020', null=True)),
                ('control_file_url', models.URLField(blank=True, max_length=50, null=True)),
                ('documentation', models.FileField(blank=True, null=True, upload_to='uploads/control_system_documentations')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.ControlSystemManufacturer')),
                ('manufacturer_contact_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Person')),
            ],
        ),
    ]
