# Generated by Django 2.2.3 on 2019-10-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20191027_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='architect_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
