# Generated by Django 2.2.3 on 2020-02-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0009_auto_20200221_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_po_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_date_of_project',
            field=models.DateField(blank=True, null=True),
        ),
    ]
