# Generated by Django 3.0.2 on 2020-09-15 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testsheet_sheet_generator'),
        ('order', '0009_auto_20200915_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='control_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ControlSystem'),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='manufacturer_contact_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Person'),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='09/15/2020', null=True),
        ),
    ]
