# Generated by Django 3.0.2 on 2020-09-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200915_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsystem',
            name='control_file_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
