# Generated by Django 2.2.3 on 2020-03-24 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200221_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_number', models.CharField(max_length=30)),
                ('date', models.DateField(default='03/25/2020', null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.Order')),
            ],
        ),
    ]
