# Generated by Django 2.2.3 on 2020-03-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_changeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='03/27/2020', null=True),
        ),
    ]
