# Generated by Django 3.0.2 on 2020-09-19 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200915_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='equipment_submittal',
            field=models.FileField(blank=True, null=True, upload_to='uploads/order_equipment_submittal'),
        ),
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='09/19/2020', null=True),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='09/19/2020', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='control_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.ControlSystem'),
        ),
    ]
