# Generated by Django 4.2.11 on 2024-08-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_controlsystem_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='08/20/2024', null=True),
        ),
    ]
