# Generated by Django 2.2.3 on 2020-03-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0012_auto_20200327_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='03/31/2020', null=True),
        ),
    ]
