# Generated by Django 3.1.3 on 2020-12-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20201117_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='techlabel',
            name='schedule_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='12/03/2020', null=True),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='12/03/2020', null=True),
        ),
    ]
