# Generated by Django 2.2.3 on 2019-11-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20191111_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='project_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
