# Generated by Django 2.2.3 on 2020-04-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0013_auto_20200331_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='04/02/2020', null=True),
        ),
    ]
