# Generated by Django 3.0.2 on 2020-09-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20200926_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='09/27/2020', null=True),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='09/27/2020', null=True),
        ),
        migrations.CreateModel(
            name='TechLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed_drawing', models.BooleanField(default=True)),
                ('schedule_drawing', models.BooleanField(default=True)),
                ('mechanical_drawing', models.BooleanField(default=True)),
                ('tech_test_sheets', models.BooleanField()),
                ('point_of_contact_name', models.CharField(max_length=50)),
                ('point_of_contact_cell_phone', models.CharField(max_length=15)),
                ('point_of_contact_office_phone', models.CharField(max_length=15)),
                ('tech_notes', models.TextField(blank=True, max_length=255, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
