# Generated by Django 2.2.3 on 2020-04-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0015_auto_20200403_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fully_settled',
            field=models.BooleanField(default=False),
        ),
    ]
