# Generated by Django 3.1.3 on 2020-12-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20201203_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techlabel',
            name='schedule_date',
            field=models.DateField(null=True),
        ),
    ]
