# Generated by Django 3.0.2 on 2020-09-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20200927_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techlabel',
            name='detailed_drawing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='techlabel',
            name='mechanical_drawing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='techlabel',
            name='point_of_contact_cell_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='techlabel',
            name='point_of_contact_office_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='techlabel',
            name='schedule_drawing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='techlabel',
            name='tech_test_sheets',
            field=models.BooleanField(default=False),
        ),
    ]
