# Generated by Django 2.2.3 on 2020-04-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0016_order_fully_settled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fully_settled',
        ),
        migrations.AddField(
            model_name='order',
            name='order_settled_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
