# Generated by Django 4.2.11 on 2024-10-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_controlsystem_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='general_notes_and_comments',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
