# Generated by Django 3.1.3 on 2020-12-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20201203_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='12/05/2020', null=True),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='12/05/2020', null=True),
        ),
        migrations.AlterField(
            model_name='techlabel',
            name='point_of_contact_cell_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='techlabel',
            name='point_of_contact_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='techlabel',
            name='point_of_contact_office_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
