# Generated by Django 4.2.11 on 2024-10-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_general_notes_and_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='10/18/2024', null=True),
        ),
    ]
