# Generated by Django 2.2.3 on 2020-09-29 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_techlabelmodel'),
        ('order', '0017_auto_20200928_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='techlabel',
            name='label_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.TechLabelModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='09/29/2020', null=True),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='09/29/2020', null=True),
        ),
    ]
