# Generated by Django 4.2.11 on 2024-11-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
        ('order', '0018_alter_controlsystem_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='11/15/2024', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposal'),
        ),
    ]
