# Generated by Django 3.0.2 on 2020-04-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0018_order_fully_settled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='04/29/2020', null=True),
        ),
    ]
