# Generated by Django 4.2.11 on 2024-12-08 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_controlsystem_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
