# Generated by Django 4.2.11 on 2024-12-28 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_controlsystem_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-proposal'], 'verbose_name': 'Order List', 'verbose_name_plural': 'Order Lists'},
        ),
        migrations.AddField(
            model_name='changeorder',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='changeorderservice',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='changeorderservice',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='changeorderservice',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='changeorderservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='controlsystem',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='controlsystem',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='controlsystem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='controlsystemmanufacturer',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='controlsystemmanufacturer',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='controlsystemmanufacturer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='techlabel',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='techlabel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='techlabel',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='techlabel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='techlabelextrafields',
            name='archive',
            field=models.BooleanField(default=False, help_text='Archive flag.'),
        ),
        migrations.AddField(
            model_name='techlabelextrafields',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='techlabelextrafields',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag.'),
        ),
        migrations.AddField(
            model_name='techlabelextrafields',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='changeorder',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='controlsystemmanufacturer',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
