# Generated by Django 3.0.2 on 2020-05-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_auto_20200503_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='05/04/2020', null=True),
        ),
    ]
