# Generated by Django 2.2.3 on 2021-03-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_auto_20210327_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='partial_job_done',
            field=models.BooleanField(default=False),
        ),
    ]
