# Generated by Django 2.2.3 on 2021-03-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_order_partial_job_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='colored_drawing',
            field=models.FileField(blank=True, null=True, upload_to='uploads/order_colored_drawing'),
        ),
        migrations.AddField(
            model_name='order',
            name='site_pictures',
            field=models.FileField(blank=True, null=True, upload_to='uploads/order_site_pictures'),
        ),
        migrations.AddField(
            model_name='order',
            name='test_sheets',
            field=models.FileField(blank=True, null=True, upload_to='uploads/order_test_sheets'),
        ),
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='03/28/2021', null=True),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='03/28/2021', null=True),
        ),
    ]
