# Generated by Django 2.2.3 on 2021-03-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_auto_20210328_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='03/29/2021', null=True),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='03/29/2021', null=True),
        ),
    ]
