# Generated by Django 2.2.3 on 2021-04-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_auto_20210331_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='04/01/2021', null=True),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='04/01/2021', null=True),
        ),
    ]
