# Generated by Django 2.2.3 on 2021-04-10 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_auto_20210410_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completion_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
