# Generated by Django 2.2.3 on 2021-04-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_auto_20210422_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pre_demo_settled_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
