# Generated by Django 2.2.3 on 2021-04-22 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0056_order_pre_demo_settled_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pre_demo_settled_value',
        ),
        migrations.AddField(
            model_name='order',
            name='pre_demo_completion_percentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
