# Generated by Django 2.2.3 on 2021-06-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0074_auto_20210608_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='06/15/2021', null=True),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='06/15/2021', null=True),
        ),
    ]
