# Generated by Django 2.2.3 on 2021-08-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0079_auto_20210810_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='08/17/2021', null=True),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='08/17/2021', null=True),
        ),
    ]
