# Generated by Django 2.2.3 on 2021-09-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0082_auto_20210911_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='invoice_adjustment',
            new_name='final_offset',
        ),
        migrations.AddField(
            model_name='order',
            name='predemo_offset',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
