# Generated by Django 2.2.3 on 2022-03-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0086_auto_20211116_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='03/19/2022', null=True),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='03/19/2022', null=True),
        ),
        migrations.CreateModel(
            name='TechLabelExtraFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('tech_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.TechLabel')),
            ],
        ),
    ]
