# Generated by Django 4.0.4 on 2022-04-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0091_alter_changeorder_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='colored_drawing_finalize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='field_draw',
            field=models.FileField(blank=True, null=True, upload_to='uploads/field_draw'),
        ),
        migrations.AddField(
            model_name='order',
            name='report_colored_drawing',
            field=models.FileField(blank=True, null=True, upload_to='uploads/report_colored_drawing'),
        ),
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='04/23/2022', null=True),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='04/23/2022', null=True),
        ),
    ]
