# Generated by Django 4.0.4 on 2022-04-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0092_order_colored_drawing_finalize_order_field_draw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='report_colored_drawing',
            field=models.FileField(blank=True, null=True, upload_to='uploads/order_colored_drawing/report'),
        ),
    ]
