# Generated by Django 4.0.4 on 2022-04-23 07:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0093_alter_order_report_colored_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='general_notes_and_comments',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
