# Generated by Django 4.0.4 on 2022-04-23 08:15

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0094_order_general_notes_and_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='general_notes_and_comments',
            field=djrichtextfield.models.RichTextField(blank=True, null=True),
        ),
    ]
