# Generated by Django 4.0.4 on 2022-04-23 08:23

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0095_alter_order_general_notes_and_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='general_notes_and_comments',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
