# Generated by Django 4.0.4 on 2022-04-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0096_alter_order_general_notes_and_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='general_notes_and_comments_finalize',
            field=models.BooleanField(default=False),
        ),
    ]
