# Generated by Django 4.0.4 on 2022-04-23 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210723_1021'),
        ('order', '0098_alter_order_architect_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='architect_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person'),
        ),
    ]
