# Generated by Django 3.2.13 on 2022-04-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0088_auto_20220429_1045'),
        ('order', '0099_alter_order_architect_name'),
    ]

    operations = [
    ]
