# Generated by Django 3.2.13 on 2023-07-06 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0103_auto_20230705_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeorder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='changeorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='changeorder',
            name='description',
        ),
        migrations.AddField(
            model_name='changeorder',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='07/06/2023', null=True),
        ),
        migrations.CreateModel(
            name='ChangeOrderService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='07/06/2023', null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('change_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.changeorder')),
            ],
        ),
    ]
