# Generated by Django 3.2.13 on 2023-07-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0104_auto_20230706_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeorderservice',
            name='date',
        ),
        migrations.AddField(
            model_name='changeorder',
            name='date',
            field=models.DateField(default='2023-07-06', null=True),
        ),
    ]
