# Generated by Django 3.2.13 on 2023-07-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0105_auto_20230706_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
