# Generated by Django 3.2.13 on 2023-09-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0106_alter_changeorder_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlsystem',
            options={'ordering': ['manufacturer']},
        ),
        migrations.AlterModelOptions(
            name='controlsystemmanufacturer',
            options={'ordering': ['manufacturer_name']},
        ),
        migrations.AlterField(
            model_name='changeorder',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='changeorderservice',
            name='change_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.changeorder'),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='09/13/2023', null=True),
        ),
    ]
