# Generated by Django 3.2.13 on 2023-09-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0107_auto_20230913_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeorder',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='09/16/2023', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='changeorder',
            unique_together={('co_number', 'order')},
        ),
    ]
