# Generated by Django 4.2.6 on 2024-05-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0109_alter_controlsystem_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlsystem',
            name='release_date',
            field=models.DateField(blank=True, default='05/11/2024', null=True),
        ),
    ]
