# Generated by Django 3.1.3 on 2020-11-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20201116_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='11/17/2020'),
        ),
    ]
