# Generated by Django 2.2.3 on 2021-01-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_auto_20201228_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='01/04/2021'),
        ),
    ]
