# Generated by Django 2.2.3 on 2021-08-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0070_auto_20210806_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default='08/09/2021'),
        ),
    ]
