# Generated by Django 2.2.3 on 2019-10-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20190921_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_person_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=55)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Person')),
            ],
            options={
                'verbose_name': 'Certificate of Insurance',
                'verbose_name_plural': 'Certificate of Insurance',
                'ordering': ['-created_on'],
            },
        ),
    ]
