# Generated by Django 2.2.3 on 2020-01-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_person_name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=55)),
                ('subject', models.CharField(max_length=100)),
                ('cc', models.CharField(blank=True, max_length=55)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certificate of Insurance',
                'verbose_name_plural': 'Certificate of Insurance',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Insurance Company Information',
                'verbose_name_plural': 'Insurance Company Information',
            },
        ),
    ]
