# Generated by Django 2.2.3 on 2019-10-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coi',
            name='email',
            field=models.EmailField(max_length=55),
        ),
    ]
