# Generated by Django 2.2.3 on 2019-12-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('coi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coi',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Person'),
        ),
    ]
