# Generated by Django 2.2.3 on 2019-11-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coi', '0003_insurancecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecompany',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
