# Generated by Django 2.2.3 on 2019-11-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coi', '0004_auto_20191130_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='coi',
            name='cc',
            field=models.EmailField(blank=True, max_length=55),
        ),
        migrations.AddField(
            model_name='coi',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
