# Generated by Django 3.1.3 on 2020-12-14 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0022_auto_20201214_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_package', models.BooleanField(default=False)),
                ('tech_package_date', models.DateTimeField(blank=True, null=True)),
                ('tech_scheduled', models.BooleanField(default=False)),
                ('tech_scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('job_completed', models.BooleanField(default=False)),
                ('job_completed_date', models.DateTimeField(blank=True, null=True)),
                ('report_out', models.BooleanField(default=False)),
                ('report_out_date', models.DateTimeField(blank=True, null=True)),
                ('invoiced', models.BooleanField(default=False)),
                ('invoiced_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'Project Process',
                'verbose_name_plural': 'Project Process',
                'ordering': ['-created_on'],
            },
        ),
    ]
