# Generated by Django 5.1.6 on 2025-03-30 06:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('tech_package', models.BooleanField(default=False)),
                ('tech_package_date', models.DateField(blank=True, null=True)),
                ('tech_scheduled', models.BooleanField(default=False)),
                ('tech_scheduled_date', models.DateField(blank=True, null=True)),
                ('job_completed', models.BooleanField(default=False)),
                ('job_completed_date', models.DateField(blank=True, null=True)),
                ('report_out', models.BooleanField(default=False)),
                ('report_out_date', models.DateField(blank=True, null=True)),
                ('invoiced', models.BooleanField(default=False)),
                ('invoiced_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'Project Process',
                'verbose_name_plural': 'Project Process',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProcessPreDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('tech_package', models.BooleanField(default=False)),
                ('tech_package_date', models.DateField(blank=True, null=True)),
                ('tech_scheduled', models.BooleanField(default=False)),
                ('tech_scheduled_date', models.DateField(blank=True, null=True)),
                ('job_completed', models.BooleanField(default=False)),
                ('job_completed_date', models.DateField(blank=True, null=True)),
                ('report_out', models.BooleanField(default=False)),
                ('report_out_date', models.DateField(blank=True, null=True)),
                ('invoiced', models.BooleanField(default=False)),
                ('invoiced_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'Project Process Pre Demo',
                'verbose_name_plural': 'Project Process Pre Demo',
                'ordering': ['-created_on'],
            },
        ),
    ]
