# Generated by Django 2.2.3 on 2021-01-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectprocess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprocess',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectprocess',
            name='invoiced_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectprocess',
            name='job_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectprocess',
            name='report_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectprocess',
            name='tech_package_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectprocess',
            name='tech_scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
