# Generated by Django 2.2.3 on 2021-03-31 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectprocess', '0004_auto_20210111_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprocess',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', unique=True),
        ),
    ]
