# Generated by Django 2.2.3 on 2021-03-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectprocess', '0006_auto_20210331_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprocess',
            name='predemo',
            field=models.BooleanField(default=False),
        ),
    ]
