# Generated by Django 2.2.3 on 2021-03-31 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_auto_20210331_0756'),
        ('projectprocess', '0007_projectprocess_predemo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprocess',
            name='predemo',
        ),
        migrations.AlterField(
            model_name='projectprocess',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.CreateModel(
            name='ProjectProcessPreDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_package', models.BooleanField(default=False)),
                ('tech_package_date', models.DateField(blank=True, null=True)),
                ('tech_scheduled', models.BooleanField(default=False)),
                ('tech_scheduled_date', models.DateField(blank=True, null=True)),
                ('job_completed', models.BooleanField(default=False)),
                ('job_completed_date', models.DateField(blank=True, null=True)),
                ('report_out', models.BooleanField(default=False)),
                ('report_out_date', models.DateField(blank=True, null=True)),
                ('invoiced', models.BooleanField(default=False)),
                ('invoiced_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'verbose_name': 'Project Process Pre Demo',
                'verbose_name_plural': 'Project Process Pre Demo',
                'ordering': ['-created_on'],
            },
        ),
    ]
