# Generated by Django 2.2.3 on 2021-07-12 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbmanagement', '0018_auto_20210601_1719'),
        ('sheetcreator', '0090_auto_20210712_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryHeatExchangerEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=20, null=True)),
                ('main_data_entry_completed', models.BooleanField(default=False)),
                ('design_data_entry_completed', models.BooleanField(default=False)),
                ('actual_data_entry_completed', models.BooleanField(default=False)),
                ('field_order', models.PositiveIntegerField(default=0)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.EquipmentDb')),
                ('equipment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.Equipment')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheetcreator.DataSheet')),
            ],
            options={
                'ordering': ['field_order'],
            },
        ),
        migrations.CreateModel(
            name='PrimaryHeatExchangerSheetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.PositiveSmallIntegerField(choices=[(1, 'Design'), (2, 'Actual')], default=1)),
                ('value', models.CharField(max_length=500)),
                ('primary_heat_exchanger_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsheetprimaryheatexchanger.PrimaryHeatExchangerEquipment')),
                ('sheet_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanagement.TestSheetField')),
            ],
        ),
    ]
