# Generated by Django 2.2.3 on 2021-07-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetprimaryheatexchanger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryheatexchangerequipment',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='primaryheatexchangerequipment',
            name='rating_btu_hour',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='primaryheatexchangerequipment',
            name='service',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
