# Generated by Django 2.2.3 on 2021-07-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsheetprimaryheatexchanger', '0002_auto_20210712_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryheatexchangerequipment',
            name='unit_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
