# Generated by Django 5.1.6 on 2025-03-02 18:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.BooleanField(default=False, help_text='Archive flag.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('validity', models.IntegerField(default=180)),
                ('note', models.TextField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estimator.estimate')),
            ],
            options={
                'verbose_name': 'Proposal List',
                'verbose_name_plural': 'Proposal Lists',
                'ordering': ['-estimate'],
            },
        ),
    ]
