# Generated by Django 4.2.11 on 2024-12-28 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
