# Generated by Django 4.2.11 on 2024-05-11 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(help_text='Maximum Upload Size: 500.0MB', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_customer', to='core.contactinfo'),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrative.typesofdocument'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('type', 'customer')},
        ),
    ]
