# Generated by Django 2.2.3 on 2020-03-20 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_auto_20200301_1915'),
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(help_text='Maximum Upload Size: 250.0MB', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='doc_customer',
                                    to='core.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('type', 'customer')},
        ),
    ]
