# Generated by Django 2.2.3 on 2021-08-09 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(help_text='Maximum Upload Size: 500.0MB', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_customer', to='core.ContactInfo'),
        ),
    ]
