# Generated by Django 2.2.3 on 2020-03-22 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0002_auto_20200320_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(help_text='Maximum Upload Size: 250.0MB', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_customer', to='core.ContactInfo'),
        ),
    ]
